import { CanonicalBrushContact } from '../engine/src/webgpuCanonical/brush'
import { CanonicalFieldBuffer, CanonicalScratchPool, createCanonicalSettleField, destroyCanonicalSettleField } from '../engine/src/webgpuCanonical/fieldBuffer'
import { CanonicalWatercolorWebGpu } from '../engine/src/webgpuCanonical/backend'
import { compositeGlOracle } from '../engine/src/webgpuCanonical/compositeOracle'
import { ribbonGlOracle, stampGlOracle } from '../engine/src/webgpuCanonical/ribbonOracle'
import { buildRibbonBands } from '../engine/src/dabs/markerRibbon'
import type { Dab } from '@grafetto/shared'
import type { CanonicalRibbonBatch, CanonicalStamp } from '../engine/src/webgpuCanonical/types'
const canvas = document.querySelector<HTMLCanvasElement>('#stage')!
const width = 256, height = 192
const bytes = new Uint8Array(256 * 256 * 4).fill(128)
const backend = await CanonicalWatercolorWebGpu.create({ canvas, width, height, paper: { bytes, width:256, height:256, origin: [0, -height], texSize: [256,256], scale: 1 } })
const dabs: Dab[] = Array.from({ length: 20 }, (_, k) => ({ x: 32 + k * 9, y: 70 + Math.sin(k / 3) * 20, size: 40, aspectRatio: 1, angle: 0, opacity: 1, pressure: .8, tiltX: 0, tiltY: 0, t: k * 10 }))
const vertices = buildRibbonBands(dabs, 1, undefined, 'ellipse', 0, 1, () => ({ ink: .14, water: .8, paperWet: .7, strength: .11, puddle: .5, pigmentPool: .3 }), true)
const batch: CanonicalRibbonBatch = { vertices, inkBlend: 'max', uniforms: { aaPx: 1, washWater: .8, waterRetain: .4, bristleCombs: 4, bristleInk: .1, tau: [1, 2, .7], worldOrigin: [0, 0], mottleSeed: [4, 9], cloudDeposit: .08, granDeposit: .12, poolBlot: 1, useAvailableWater: false } }
const gpuErrors: string[] = []
backend.device.addEventListener('uncapturederror', event => { gpuErrors.push(event.error.message); document.querySelector('#status')!.textContent = event.error.message })
backend.appendPreparedRibbon(batch); await backend.whenIdle(); backend.presentField(backend.fields.pigment)
const snapshot = await backend.readSnapshot()
const nonzero = Object.fromEntries(Object.entries(snapshot.fields).map(([name, data]) => [name, data.reduce((sum, b) => sum + +(b > 0), 0)]))
const reference=ribbonGlOracle(batch,width,height)
const parity=Object.fromEntries(Object.entries(reference).map(([name,bytes])=>{const gpu=snapshot.fields[name as keyof typeof snapshot.fields];let changed=0,max=0;for(let k=0;k<bytes.length;k++){const d=Math.abs(bytes[k]-gpu[k]);if(d)changed++;max=Math.max(max,d)}return[name,{changed,max}]}))
backend.clear();
const stamp: CanonicalStamp={center:[32,70],radius:20,aspect:1,angle:0,pressure:.8,opacity:.14,nibShape:'ellipse',cornerRadius:0,inkEdge:.4,inkWater:.8,paperWet:.7,inkStrength:.11,puddle:.5,pigmentPool:.3,acrossLocal:[1,0],inkClip:0,inkBlend:'max',uniforms:batch.uniforms};
backend.appendPreparedStamp(stamp);await backend.whenIdle();const stampSnapshot=await backend.readSnapshot();const stampReference=stampGlOracle(stamp,width,height);const stampParity=Object.fromEntries(Object.entries(stampReference).map(([name,bytes])=>{const gpu=stampSnapshot.fields[name as keyof typeof stampSnapshot.fields];let changed=0,max=0;for(let k=0;k<bytes.length;k++){const d=Math.abs(bytes[k]-gpu[k]);if(d)changed++;max=Math.max(max,d)}return[name,{changed,max}]}));
const original=backend.createField('QA original',width,height),out=backend.createField('QA canonical output',width,height);backend.restoreSnapshot(snapshot);const compositeUniforms={paperOrigin:[0,-height] as const,paperTexSize:[256,256] as const,paperScale:[1,1] as const,fieldOffset:[4,9] as const,inkSmoothPx:0,water:.8,inkStrength:.8,spreadPx:4,edgeWander:.2,edgeSoft:.1,bristleCombs:4,dryContact:0,granulation:.2,wetEdge:.2,wetEdgeRadiusPx:4,tideLo:.3,tideHi:.7,paperRim:.1,opacity:1,pigmentOpacity:.2,debugView:0,rectComposite:true,migrate:0};backend.compositeInto(original,out,compositeUniforms);await backend.whenIdle();backend.present(out);const compositeBytes=await backend.readField(out),compositeReference=compositeGlOracle(snapshot,bytes,compositeUniforms);let compositeChanged=0,compositeMax=0;for(let k=0;k<compositeBytes.length;k++){const d=Math.abs(compositeBytes[k]-compositeReference[k]);if(d)compositeChanged++;compositeMax=Math.max(compositeMax,d)}
backend.brushContact([2/width,2/height],.84,[0,0,1,1]);await backend.whenIdle();const brushSnapshot=await backend.readSnapshot();let zeroBrushChanged=0;for(const key of ['pigment','color'] as const)for(let k=0;k<snapshot.fields[key].length;k++)zeroBrushChanged+=+(snapshot.fields[key][k]!==brushSnapshot.fields[key][k]);
const copied=backend.createField('QA copy/clear',width,height);backend.copyField(backend.fields.pigment,copied);backend.clearField(copied,[20,30,7,9]);const copiedBytes=await backend.readField(copied);let copyClearChanged=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++)for(let ch=0;ch<4;ch++){const k=(y*width+x)*4+ch,expected=x>=20&&x<27&&y>=30&&y<39?0:brushSnapshot.fields.pigment[k];copyClearChanged+=+(copiedBytes[k]!==expected)}
backend.clearField(copied);backend.copyRegion(backend.fields.pigment,copied,[20,30],[50,60],[7,9]);const regionBytes=await backend.readField(copied);let copyRegionChanged=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++)for(let ch=0;ch<4;ch++){const k=(y*width+x)*4+ch,expected=x>=50&&x<57&&y>=60&&y<69?brushSnapshot.fields.pigment[((y-30)*width+x-30)*4+ch]:0;copyRegionChanged+=+(regionBytes[k]!==expected)}
backend.clear();for(const phase of ['coverage','pigment','color'] as const)backend.appendPreparedStamp(stamp,phase);await backend.whenIdle();const stampPhases=await backend.readSnapshot();let phaseChanged=0;for(const key of ['coverage','pigment','color'] as const)for(let k=0;k<stampSnapshot.fields[key].length;k++)phaseChanged+=+(stampPhases.fields[key][k]!==stampSnapshot.fields[key][k]);
const flowBytes=new Uint8Array(width*height*4);for(let k=0;k<flowBytes.length;k+=4)flowBytes.set([220,190,100,255],k);backend.upload(backend.fields.flow,flowBytes);backend.copyField(backend.fields.coverage,backend.fields.water);const activeBefore=await backend.readSnapshot();backend.brushContact([2/width,2/height],.2,[0,0,1,1]);await backend.whenIdle();const activeAfter=await backend.readSnapshot();let activeBrushChanged=0;const activeBrushMassDelta=[];for(const key of ['pigment','color'] as const)for(let ch=0;ch<4;ch++){let delta=0;for(let k=ch;k<activeBefore.fields[key].length;k+=4){delta+=activeAfter.fields[key][k]-activeBefore.fields[key][k];activeBrushChanged+=+(activeAfter.fields[key][k]!==activeBefore.fields[key][k]);}activeBrushMassDelta.push(delta);}
backend.clear();const shiftedVertices=vertices.slice();for(let i=0;i<shiftedVertices.length;i+=11){shiftedVertices[i]+=512;shiftedVertices[i+1]+=768}
const shiftedBatch={...batch,vertices:shiftedVertices,uniforms:{...batch.uniforms,worldOrigin:[512,-768] as const}};backend.appendPreparedRibbon(shiftedBatch);await backend.whenIdle();const shiftedSnapshot=await backend.readSnapshot(),shiftedReference=ribbonGlOracle(shiftedBatch,width,height)
const nonzeroOriginParity=Object.fromEntries(Object.entries(shiftedReference).map(([name,ref])=>{const gpu=shiftedSnapshot.fields[name as keyof typeof shiftedSnapshot.fields];let changed=0,max=0;for(let k=0;k<ref.length;k++){const d=Math.abs(ref[k]-gpu[k]);changed+=+(d>0);max=Math.max(max,d)}return[name,{changed,max}]}))
const scissorP=backend.createField('scissor P',width,height),scissorC=backend.createField('scissor C',width,height),sentinel=new Uint8Array(width*height*4).fill(77);backend.upload(scissorP,sentinel);backend.upload(scissorC,sentinel)
const scissorEncoder=backend.device.createCommandEncoder(),scissorBuffers=new CanonicalBrushContact(backend.device).encode({device:backend.device,encoder:scissorEncoder,nearest:backend.nearest,linear:backend.linear},{pigment:backend.fields.pigment,color:backend.fields.color,flow:backend.fields.flow,water:backend.fields.water,outPigment:scissorP,outColor:scissorC},[1/width,1/height],.1,[0,0,1,1],[30,40,8,9]);backend.device.queue.submit([scissorEncoder.finish()]);await backend.whenIdle();scissorBuffers.forEach(b=>b.destroy());let scissorOutsideChanged=0
for(const field of [scissorP,scissorC]){const pixels=await backend.readField(field);for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(!(x>=30&&x<38&&y>=height-49&&y<height-40))for(let c=0;c<4;c++)scissorOutsideChanged+=+(pixels[(y*width+x)*4+c]!==77)}backend.destroyField(scissorP);backend.destroyField(scissorC)
const singleBrush=new CanonicalBrushContact(backend.device),singleBrushParity:Record<string,{changed:number;active:number;transported:number}>={}
for(const filter of ['nearest','linear'] as const)for(const stepPixels of [1,2]){
 const w=32,h=24,make=(name:string,filter:'nearest'|'linear'='nearest')=>backend.createField(name,w,h,filter)
 const p=make('single fixture P'),c=make('single fixture C'),flow=make('single fixture flow','linear'),water=make('single fixture wet',filter),pairP=make('paired output P'),pairC=make('paired output C'),singleP=make('single output P'),singleC=make('single output C')
 const pb=new Uint8Array(w*h*4),cb=new Uint8Array(w*h*4),fb=new Uint8Array(w*h*4),wb=new Uint8Array(w*h*4)
 for(let y=0;y<h;y++)for(let x=0;x<w;x++)for(let ch=0;ch<4;ch++){const k=(y*w+x)*4+ch;pb[k]=(x+y+ch)%7===0?254:(x+y+ch)%5===0?1:(x*37+y*19+ch*61)%220;cb[k]=(x*3+y+ch)%9===0?253:(x*11+y*23+ch*47)%180;fb[k]=ch===0?220:ch===1?80:ch===2?209:255;wb[k]=ch===3?((x+y)%5===0?0:(x+y)%7===0?3:190):0}
 for(const [field,bytes] of [[p,pb],[c,cb],[flow,fb],[water,wb]] as const)backend.upload(field,bytes)
 const initial=new Uint8Array(w*h*4).fill(77);for(const out of [pairP,pairC,singleP,singleC])backend.upload(out,initial)
 const encoder=backend.device.createCommandEncoder(),ctx={device:backend.device,encoder,nearest:backend.nearest,linear:backend.linear},step=[stepPixels/w,stepPixels/h] as const,scissor=[3,4,w-6,h-8] as const,rectangle=[0,0,1,1] as const
 const buffers=[...singleBrush.encode(ctx,{pigment:p,color:c,flow,water,outPigment:pairP,outColor:pairC},step,.15,rectangle,scissor),...singleBrush.encodeSingle(ctx,{pigment:p,color:c,flow,water,out:singleP},'pigment',step,.15,rectangle,scissor),...singleBrush.encodeSingle(ctx,{pigment:p,color:c,flow,water,out:singleC},'color',step,.15,rectangle,scissor)]
 backend.device.queue.submit([encoder.finish()]);await backend.whenIdle();buffers.forEach(b=>b.destroy());let changed=0,active=0,transported=0
 for(const [pair,single] of [[pairP,singleP],[pairC,singleC]]){const a=await backend.readField(pair),b=await backend.readField(single);for(let k=0;k<a.length;k++){changed+=+(a[k]!==b[k]);active+=+(a[k]!==77);const x=Math.floor(k/4)%w,y=Math.floor(k/(w*4));if(x>=3&&x<w-3&&y>=4&&y<h-4)transported+=+(a[k]!==((pair===pairP?pb:cb)[k]))}}
 singleBrushParity[`${filter}-step${stepPixels}`]={changed,active,transported};for(const field of [p,c,flow,water,pairP,pairC,singleP,singleC])backend.destroyField(field)
}
const ownerSource=new CanonicalFieldBuffer(backend,4,4),ownerA=new CanonicalFieldBuffer(backend,4,4),ownerB=new CanonicalFieldBuffer(backend,4,4)
const payloadA=Uint8Array.from({length:64},(_,k)=>k),payloadB=Uint8Array.from({length:64},(_,k)=>255-k),ownerEncoder=backend.device.createCommandEncoder()
const ownerScope=backend.encodeOwnerCommands(ownerEncoder,()=>{ownerSource.upload(payloadA);ownerSource.copyTo(ownerA);ownerSource.upload(payloadB);ownerSource.copyTo(ownerB)})
backend.device.queue.submit([ownerEncoder.finish()]);await backend.whenIdle();ownerScope.release()
let ownerOrderingChanged=0;for(const [field,expected] of [[ownerA,payloadA],[ownerB,payloadB]] as const){const actual=await field.readBytes();for(let k=0;k<64;k++)ownerOrderingChanged+=+(actual[k]!==expected[k])}
ownerB.clear();ownerA.copyRegionInto(ownerB,0,0,1,1,2,2);const ownerRegion=await ownerB.readBytes();let ownerGlRegionChanged=0
for(let y=0;y<4;y++)for(let x=0;x<4;x++)for(let c=0;c<4;c++){const expected=x>=1&&x<3&&y>=1&&y<3?payloadA[((y+1)*4+x-1)*4+c]:0;ownerGlRegionChanged+=+(ownerRegion[(y*4+x)*4+c]!==expected)}
const retiringSource=new CanonicalFieldBuffer(backend,4,4),retiringOut=new CanonicalFieldBuffer(backend,4,4),retirementEncoder=backend.device.createCommandEncoder();const retirementScope=backend.encodeOwnerCommands(retirementEncoder,()=>{retiringSource.upload(payloadA);retiringSource.copyTo(retiringOut)});retiringSource.destroy();backend.device.queue.submit([retirementEncoder.finish()]);await backend.whenIdle();retirementScope.release();retirementScope.release();const retirementBytes=await retiringOut.readBytes();const ownerRetirementChanged=retirementBytes.reduce((n,b,k)=>n+ +(b!==payloadA[k]),0);retiringOut.destroy()
const ownerPool=new CanonicalScratchPool(backend),lease=ownerPool.acquire(4,4);ownerPool.release(lease);const sameLease=ownerPool.acquire(4,4);const ownerPoolReused=lease===sameLease;ownerPool.release(sameLease);ownerPool.destroy()
const ownerSettle=createCanonicalSettleField(backend,4,4),ownerFilterExact=ownerSettle.a.field.filter==='nearest'&&ownerSettle.band.field.filter==='nearest'&&ownerSettle.mask.field.filter==='linear'&&ownerSettle.pressure.field.filter==='linear';destroyCanonicalSettleField(ownerSettle)
ownerSource.destroy();ownerA.destroy();ownerB.destroy()
Object.assign(window, { __canonicalWebGpu: backend, __canonicalBatch: batch, __canonicalStage: { singleBrushParity, ownerRetirementChanged, scissorOutsideChanged, nonzeroOriginParity, ownerOrderingChanged,ownerGlRegionChanged,ownerPoolReused,ownerFilterExact, activeBrushChanged,activeBrushMassDelta,copyClearChanged,copyRegionChanged,phaseChanged,zeroBrushChanged,compositeParity:{changed:compositeChanged,max:compositeMax},stampParity, parity, gpuErrors, nonzero, vertices: vertices.length / 11 } })
document.querySelector('#status')!.textContent = JSON.stringify({ stage: 'production ribbon deposit only — settle/composite unavailable', nonzero, vertices: vertices.length / 11 })
