import { CanonicalWatercolorWebGpu } from '../engine/src/webgpuCanonical/backend'
import { compositeGlOracle } from '../engine/src/webgpuCanonical/compositeOracle'
import { ribbonGlOracle, stampGlOracle } from '../engine/src/webgpuCanonical/ribbonOracle'
import { buildRibbonBands } from '../engine/src/dabs/markerRibbon'
import type { Dab } from '@grafetto/shared'
import type { CanonicalRibbonBatch, CanonicalStamp } from '../engine/src/webgpuCanonical/types'
const canvas = document.querySelector<HTMLCanvasElement>('#stage')!
const width = 256, height = 192
const bytes = new Uint8Array(256 * 256 * 4).fill(128)
const backend = await CanonicalWatercolorWebGpu.create({ canvas, width, height, paper: { bytes, width:256, height:256, origin: [0, -height], texSize: [256,256], scale: 1 } })
const dabs: Dab[] = Array.from({ length: 20 }, (_, k) => ({ x: 32 + k * 9, y: 70 + Math.sin(k / 3) * 20, size: 40, aspectRatio: 1, angle: 0, opacity: 1, pressure: .8, tiltX: 0, tiltY: 0, t: k * 10 }))
const vertices = buildRibbonBands(dabs, 1, undefined, 'ellipse', 0, 1, () => ({ ink: .14, water: .8, paperWet: .7, strength: .11, puddle: .5, pigmentPool: .3 }), true)
const batch: CanonicalRibbonBatch = { vertices, inkBlend: 'max', uniforms: { aaPx: 1, washWater: .8, waterRetain: .4, bristleCombs: 4, bristleInk: .1, tau: [1, 2, .7], worldOrigin: [0, -height], mottleSeed: [4, 9], cloudDeposit: .08, granDeposit: .12, poolBlot: 1, useAvailableWater: false } }
const gpuErrors: string[] = []
backend.device.addEventListener('uncapturederror', event => { gpuErrors.push(event.error.message); document.querySelector('#status')!.textContent = event.error.message })
backend.appendPreparedRibbon(batch); await backend.whenIdle(); backend.presentField(backend.fields.pigment)
const snapshot = await backend.readSnapshot()
const nonzero = Object.fromEntries(Object.entries(snapshot.fields).map(([name, data]) => [name, data.reduce((sum, b) => sum + +(b > 0), 0)]))
const reference=ribbonGlOracle(batch,width,height)
const parity=Object.fromEntries(Object.entries(reference).map(([name,bytes])=>{const gpu=snapshot.fields[name as keyof typeof snapshot.fields];let changed=0,max=0;for(let k=0;k<bytes.length;k++){const d=Math.abs(bytes[k]-gpu[k]);if(d)changed++;max=Math.max(max,d)}return[name,{changed,max}]}))
backend.clear();
const stamp: CanonicalStamp={center:[32,70],radius:20,aspect:1,angle:0,pressure:.8,opacity:.14,nibShape:'ellipse',cornerRadius:0,inkEdge:.4,inkWater:.8,paperWet:.7,inkStrength:.11,puddle:.5,pigmentPool:.3,acrossLocal:[1,0],inkClip:0,inkBlend:'max',uniforms:batch.uniforms};
backend.appendPreparedStamp(stamp);await backend.whenIdle();const stampSnapshot=await backend.readSnapshot();const stampReference=stampGlOracle(stamp,width,height);const stampParity=Object.fromEntries(Object.entries(stampReference).map(([name,bytes])=>{const gpu=stampSnapshot.fields[name as keyof typeof stampSnapshot.fields];let changed=0,max=0;for(let k=0;k<bytes.length;k++){const d=Math.abs(bytes[k]-gpu[k]);if(d)changed++;max=Math.max(max,d)}return[name,{changed,max}]}));
const original=backend.createField('QA original',width,height),out=backend.createField('QA canonical output',width,height);backend.restoreSnapshot(snapshot);const compositeUniforms={paperOrigin:[0,-height] as const,paperTexSize:[256,256] as const,paperScale:[1,1] as const,fieldOffset:[4,9] as const,inkSmoothPx:0,water:.8,inkStrength:.8,spreadPx:4,edgeWander:.2,edgeSoft:.1,bristleCombs:4,dryContact:0,granulation:.2,wetEdge:.2,wetEdgeRadiusPx:4,tideLo:.3,tideHi:.7,paperRim:.1,opacity:1,pigmentOpacity:.2,debugView:0,rectComposite:true,migrate:0};backend.compositeInto(original,out,compositeUniforms);await backend.whenIdle();backend.present(out);const compositeBytes=await backend.readField(out),compositeReference=compositeGlOracle(snapshot,bytes,compositeUniforms);let compositeChanged=0,compositeMax=0;for(let k=0;k<compositeBytes.length;k++){const d=Math.abs(compositeBytes[k]-compositeReference[k]);if(d)compositeChanged++;compositeMax=Math.max(compositeMax,d)}
backend.brushContact([2/width,2/height],.84,[0,0,1,1]);await backend.whenIdle();const brushSnapshot=await backend.readSnapshot();let zeroBrushChanged=0;for(const key of ['pigment','color'] as const)for(let k=0;k<snapshot.fields[key].length;k++)zeroBrushChanged+=+(snapshot.fields[key][k]!==brushSnapshot.fields[key][k]);
const copied=backend.createField('QA copy/clear',width,height);backend.copyField(backend.fields.pigment,copied);backend.clearField(copied,[20,30,7,9]);const copiedBytes=await backend.readField(copied);let copyClearChanged=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++)for(let ch=0;ch<4;ch++){const k=(y*width+x)*4+ch,expected=x>=20&&x<27&&y>=30&&y<39?0:brushSnapshot.fields.pigment[k];copyClearChanged+=+(copiedBytes[k]!==expected)}
backend.clearField(copied);backend.copyRegion(backend.fields.pigment,copied,[20,30],[50,60],[7,9]);const regionBytes=await backend.readField(copied);let copyRegionChanged=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++)for(let ch=0;ch<4;ch++){const k=(y*width+x)*4+ch,expected=x>=50&&x<57&&y>=60&&y<69?brushSnapshot.fields.pigment[((y-30)*width+x-30)*4+ch]:0;copyRegionChanged+=+(regionBytes[k]!==expected)}
backend.clear();for(const phase of ['coverage','pigment','color'] as const)backend.appendPreparedStamp(stamp,phase);await backend.whenIdle();const stampPhases=await backend.readSnapshot();let phaseChanged=0;for(const key of ['coverage','pigment','color'] as const)for(let k=0;k<stampSnapshot.fields[key].length;k++)phaseChanged+=+(stampPhases.fields[key][k]!==stampSnapshot.fields[key][k]);
const flowBytes=new Uint8Array(width*height*4);for(let k=0;k<flowBytes.length;k+=4)flowBytes.set([220,190,100,255],k);backend.upload(backend.fields.flow,flowBytes);backend.copyField(backend.fields.coverage,backend.fields.water);const activeBefore=await backend.readSnapshot();backend.brushContact([2/width,2/height],.2,[0,0,1,1]);await backend.whenIdle();const activeAfter=await backend.readSnapshot();let activeBrushChanged=0;const activeBrushMassDelta=[];for(const key of ['pigment','color'] as const)for(let ch=0;ch<4;ch++){let delta=0;for(let k=ch;k<activeBefore.fields[key].length;k+=4){delta+=activeAfter.fields[key][k]-activeBefore.fields[key][k];activeBrushChanged+=+(activeAfter.fields[key][k]!==activeBefore.fields[key][k]);}activeBrushMassDelta.push(delta);}
Object.assign(window, { __canonicalWebGpu: backend, __canonicalBatch: batch, __canonicalStage: { activeBrushChanged,activeBrushMassDelta,copyClearChanged,copyRegionChanged,phaseChanged,zeroBrushChanged,compositeParity:{changed:compositeChanged,max:compositeMax},stampParity, parity, gpuErrors, nonzero, vertices: vertices.length / 11 } })
document.querySelector('#status')!.textContent = JSON.stringify({ stage: 'production ribbon deposit only — settle/composite unavailable', nonzero, vertices: vertices.length / 11 })
