import{expect,it,vi}from'vitest'
const trace=vi.hoisted(()=>({events:[]as string[],commands:[]as CanonicalDrawCommand[]}))
vi.mock('./PreparedGlSourceDraw',()=>({createPreparedGlSourcePort:(input:{bindCurrentCanonical:()=>unknown})=>({bindCurrentCanonical:input.bindCurrentCanonical,clear:()=>trace.events.push('clear'),copy:()=>trace.events.push('copy'),draw:(command:CanonicalDrawCommand)=>{trace.events.push('draw');trace.commands.push(structuredClone(command))},basePlusFilm:()=>trace.events.push('sum')})}))
import{OwnedGlPreparedSource,type PreparedOwnedComposite}from'./OwnedGlPreparedSource'
import type{OwnedGlSourceFields}from'./OwnedGlSourceFields'
import type{RibbonPasses,RibbonPassesContext}from'../../../../apps/web/src/engine/src/raster/RibbonPasses'
import type{WatercolorPasses}from'../../../../apps/web/src/engine/src/raster/WatercolorPasses'
import type{CanonicalDrawCommand}from'../../../../apps/web/src/engine/src/dabs/canonicalStrokeChunk'
it('actual adapter keeps own field bindings across chunks and cannot touch a newer presentation on retirement',()=>{
 trace.events=[];const release=vi.fn(),newerRelease=vi.fn(),composite=vi.fn()
 const fields=Object.fromEntries(['presentation','original','coverage','coverageFilm','pigmentLoad','pigmentBase','pigmentFilm','colourLoad','colourBase','colourFilm','solventLoad','solventBase','solventFilm'].map(role=>[role,{role}]))
 const lease={fields,release}as unknown as OwnedGlSourceFields
 const owner=new OwnedGlPreparedSource({lease,context:{}as RibbonPassesContext,ribbon:{drawRibbonCompositeRect:composite}as unknown as RibbonPasses,watercolor:{}as WatercolorPasses})
 const command={kind:'ribbon',phase:'solvent',batch:{vertices:new Float32Array(11),inkBlend:'max',uniforms:{}}}as CanonicalDrawCommand
 const c={preset:{hardness:1},profile:{normalizeDeposit:false},bounds:{minX:1,minY:1,maxX:2,maxY:2}}as PreparedOwnedComposite
 owner.paint({commands:[command],rect:[0,0,1,1],film:true,waterOnly:true,composite:c});const boundary=trace.events.length
 owner.paint({commands:[command],rect:[0,0,1,1],film:true,waterOnly:true,composite:c})
 expect(trace.events.slice(boundary)).toEqual(['draw','sum']);expect(composite).toHaveBeenCalledTimes(2)
 expect(composite.mock.calls[0][0].buffer).toBe(fields.presentation);expect(composite.mock.calls[0][4]).toBe(fields.original)
 owner.retire();owner.retire();expect(release).toHaveBeenCalledTimes(1);expect(newerRelease).not.toHaveBeenCalled();expect(()=>owner.paint({commands:[],rect:null,film:true,waterOnly:true,composite:c})).toThrow('Retired')
})
it('retained immutable source is replayed only into its own fields after exact epoch/token validation',()=>{
 trace.events=[];const writes:string[]=[],roles=['presentation','original','coverage','coverageFilm','pigmentLoad','pigmentBase','pigmentFilm','colourLoad','colourBase','colourFilm','solventLoad','solventBase','solventFilm'];const fields=Object.fromEntries(roles.map(role=>[role,{width:1024,height:1024,texture:{},role}]))as unknown as OwnedGlSourceFields['fields'];const release=vi.fn(),composite=vi.fn(),owner=new OwnedGlPreparedSource({lease:{fields,release,bytes:52*1024*1024,resources:roles.map(role=>({identity:fields[role as keyof typeof fields].texture,role:role==='presentation'?'presentation'as const:'canonical-source'as const,width:1024,height:1024}))},context:{}as RibbonPassesContext,ribbon:{drawRibbonCompositeRect:composite}as unknown as RibbonPasses,watercolor:{}as WatercolorPasses,retainForRebase:true,ownerToken:{layerId:'L',gesture:3}});
 const vertices=new Float32Array(11),command={kind:'ribbon',phase:'solvent',batch:{vertices,inkBlend:'max',uniforms:{}}}as CanonicalDrawCommand,c={preset:{hardness:1},profile:{normalizeDeposit:false},bounds:{minX:1,minY:1,maxX:2,maxY:2}}as PreparedOwnedComposite;
 owner.paint({commands:[command],rect:[0,0,1,1],film:true,waterOnly:true,composite:c});vertices[0]=NaN;c.bounds.minX=999;
 const predecessor=Object.fromEntries(['presentation','original','coverage','pigmentLoad','colourLoad','solventLoad'].map(role=>[role,{width:1024,height:1024,texture:{},copyTo:(destination:unknown)=>{expect(destination).toBe(fields[role as keyof typeof fields]);writes.push(role)}}]))as unknown as Parameters<OwnedGlPreparedSource['rebaseFromPredecessor']>[0]['fields'];
 const base={ownerToken:owner.rebaseToken!,layerId:'L',predecessorGesture:1,expectedEpoch:0,nextEpoch:1,fields:predecessor};expect(()=>owner.rebaseFromPredecessor({...base,ownerToken:{}})).toThrow('owner');expect(()=>owner.rebaseFromPredecessor({...base,fields:{...predecessor,coverage:fields.coverage}})).toThrow('feedback');expect(()=>owner.rebaseFromPredecessor({...base,predecessorGesture:3})).toThrow('future');expect(writes).toHaveLength(0);owner.rebaseFromPredecessor(base);expect((trace.commands.at(-1)as Extract<CanonicalDrawCommand,{kind:'ribbon'}>).batch.vertices[0]).toBe(0);expect(writes).toEqual(['presentation','original','coverage','pigmentLoad','colourLoad','solventLoad']);expect(owner.epoch).toBe(1);expect(composite.mock.calls.at(-1)?.[1].minX).toBe(1);expect(()=>owner.rebaseFromPredecessor(base)).toThrow('epoch');expect(writes).toHaveLength(6);expect(release).not.toHaveBeenCalled();composite.mockImplementationOnce(()=>{throw Error('GPU submission rejected')});expect(()=>owner.rebaseFromPredecessor({...base,expectedEpoch:1,nextEpoch:2})).toThrow('GPU submission rejected');expect(owner.epoch).toBe(1);expect(release).not.toHaveBeenCalled();expect(()=>owner.paint({commands:[command],rect:null,film:true,waterOnly:true,composite:c})).toThrow('Poisoned');owner.retire();expect(owner.retainedPayloadBytes).toBe(0);expect(()=>owner.rebaseFromPredecessor({...base,expectedEpoch:1,nextEpoch:2})).toThrow('unavailable');
})
