#!/usr/bin/env python3
"""The watercolour stroke archive (docs/reference/strokes, #536).

Ilya paints numbered strokes on a sheet with a coin on it, photographs the
sheet while the newest stroke dries (the "wet" series), and once more when the
whole sheet is dry. This script turns each photo into the crop of one stroke,
at one scale for the whole archive, and keeps archive.json and the viewer's
archive.js in step.

  refs.py sheet  <sheet> --coin 10rub [--paper "..."] [--note "..."]
  refs.py wet    <sheet> <stroke> <photo> --box x0,y0,x1,y1 --coin-edge x0,y0,x1,y1 [--label "..."]
  refs.py dry    <sheet> <photo> --coin-edge x0,y0,x1,y1 --stroke N:x0,y0,x1,y1 [--stroke ...]
  refs.py label  <sheet> <stroke> "<label>" [--tags a,b]
  refs.py build

Boxes and coin edges are pixel coordinates in the photo as the camera stored
it (EXIF rotation applied). `--coin-edge` is two points on opposite sides of
the coin, i.e. its diameter; the crop is rescaled to PX_PER_MM. The time of a
photo is its EXIF DateTimeOriginal; a wet photo's age is counted from the
first photo of the same stroke.
"""
import argparse
import json
import math
import os
import sys
from datetime import datetime

from PIL import Image, ImageOps

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..', 'docs', 'reference', 'strokes'))
ARCHIVE = os.path.join(ROOT, 'archive.json')
PX_PER_MM = 12
COINS_MM = {'1rub': 20.5, '2rub': 23.0, '5rub': 25.0, '10rub': 22.0, '50eurocent': 24.25}
JPEG_QUALITY = 88


def load():
    if not os.path.exists(ARCHIVE):
        return {'pxPerMm': PX_PER_MM, 'sheets': []}
    with open(ARCHIVE, encoding='utf-8') as f:
        return json.load(f)


def save(a):
    with open(ARCHIVE, 'w', encoding='utf-8') as f:
        json.dump(a, f, ensure_ascii=False, indent=1)
        f.write('\n')
    build(a)


def build(a=None):
    """archive.js - the same data as a script, so index.html opens from disk
    (a file:// page cannot fetch a JSON file)."""
    a = a or load()
    with open(os.path.join(ROOT, 'archive.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by scripts/strokes/refs.py from archive.json - do not edit.\n')
        f.write('window.STROKE_ARCHIVE = ')
        json.dump(a, f, ensure_ascii=False)
        f.write('\n')


def sheet_of(a, sid):
    for s in a['sheets']:
        if s['id'] == sid:
            return s
    sys.exit(f'no sheet {sid!r}: add it with `refs.py sheet {sid} --coin ...`')


def stroke_of(s, n):
    for st in s['strokes']:
        if st['n'] == n:
            return st
    st = {'n': n, 'label': '', 'tags': [], 'wet': [], 'dry': None}
    s['strokes'].append(st)
    s['strokes'].sort(key=lambda x: x['n'])
    return st


def open_photo(path):
    im = ImageOps.exif_transpose(Image.open(path))
    exif = Image.open(path).getexif()
    taken = exif.get_ifd(0x8769).get(36867) or exif.get(306)
    t = datetime.strptime(taken, '%Y:%m:%d %H:%M:%S').isoformat() if taken else None
    return im.convert('RGB'), t


def box(s):
    v = [float(x) for x in s.split(',')]
    if len(v) != 4:
        sys.exit(f'expected x0,y0,x1,y1, got {s!r}')
    return v


def scale_of(sheet, args):
    """Photo px per mm: from the coin's diameter, or - a photo without the
    coin - from any segment of known length (`--ref-edge`, `--ref-mm`), e.g.
    the A4 sheet's short side, 210 mm."""
    if getattr(args, 'coin_edge', None):
        x0, y0, x1, y1 = box(args.coin_edge)
        return math.hypot(x1 - x0, y1 - y0) / COINS_MM[sheet['coin']]
    if getattr(args, 'ref_edge', None) and getattr(args, 'ref_mm', None):
        x0, y0, x1, y1 = box(args.ref_edge)
        return math.hypot(x1 - x0, y1 - y0) / args.ref_mm
    sys.exit('need --coin-edge, or --ref-edge with --ref-mm')


def cut(im, b, px_per_mm, out):
    x0, y0, x1, y1 = b
    crop = im.crop((int(x0), int(y0), int(x1), int(y1)))
    k = PX_PER_MM / px_per_mm
    crop = crop.resize((max(1, round(crop.width * k)), max(1, round(crop.height * k))), Image.LANCZOS)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    crop.save(out, quality=JPEG_QUALITY)
    return crop.size


def rel(p):
    return os.path.relpath(p, ROOT).replace(os.sep, '/')


def cmd_sheet(args):
    a = load()
    if args.coin not in COINS_MM:
        sys.exit(f'coin one of {", ".join(COINS_MM)}')
    for s in a['sheets']:
        if s['id'] == args.sheet:
            s.update(coin=args.coin, paper=args.paper or s.get('paper', ''), note=args.note or s.get('note', ''))
            save(a)
            return
    a['sheets'].append({'id': args.sheet, 'coin': args.coin, 'paper': args.paper or '', 'note': args.note or '', 'strokes': []})
    save(a)


def cmd_wet(args):
    a = load()
    s = sheet_of(a, args.sheet)
    st = stroke_of(s, args.stroke)
    im, t = open_photo(args.photo)
    k = scale_of(s, args)
    i = len(st['wet']) + 1
    out = os.path.join(ROOT, 'img', s['id'], f'{args.stroke:03d}-wet-{i:02d}.jpg')
    w, h = cut(im, box(args.box), k, out)
    first = next((x['t'] for x in st['wet'] if x['t']), None)
    age = (datetime.fromisoformat(t) - datetime.fromisoformat(first)).total_seconds() if t and first else (0 if t else None)
    st['wet'].append({'src': rel(out), 't': t, 'ageS': age, 'w': w, 'h': h, 'photo': os.path.basename(args.photo)})
    if args.label:
        st['label'] = args.label
    save(a)
    print(rel(out), f'{w}x{h}', f'age {age}s' if age is not None else 'no EXIF time')


def cmd_dry(args):
    a = load()
    s = sheet_of(a, args.sheet)
    im, t = open_photo(args.photo)
    k = scale_of(s, args)
    s['dryPhotoT'] = t
    for spec in args.stroke:
        n, b = spec.split(':', 1)
        st = stroke_of(s, int(n))
        out = os.path.join(ROOT, 'img', s['id'], f'{int(n):03d}-dry.jpg')
        w, h = cut(im, box(b), k, out)
        st['dry'] = {'src': rel(out), 't': t, 'w': w, 'h': h, 'photo': os.path.basename(args.photo)}
        print(rel(out), f'{w}x{h}')
    save(a)


def cmd_label(args):
    a = load()
    st = stroke_of(sheet_of(a, args.sheet), args.stroke)
    st['label'] = args.label
    if args.tags is not None:
        st['tags'] = [x.strip() for x in args.tags.split(',') if x.strip()]
    save(a)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest='cmd', required=True)
    q = sub.add_parser('sheet'); q.add_argument('sheet'); q.add_argument('--coin', required=True); q.add_argument('--paper'); q.add_argument('--note')
    q = sub.add_parser('wet'); q.add_argument('sheet'); q.add_argument('stroke', type=int); q.add_argument('photo')
    q.add_argument('--box', required=True); q.add_argument('--coin-edge'); q.add_argument('--ref-edge'); q.add_argument('--ref-mm', type=float); q.add_argument('--label')
    q = sub.add_parser('dry'); q.add_argument('sheet'); q.add_argument('photo')
    q.add_argument('--coin-edge'); q.add_argument('--ref-edge'); q.add_argument('--ref-mm', type=float); q.add_argument('--stroke', action='append', required=True)
    q = sub.add_parser('label'); q.add_argument('sheet'); q.add_argument('stroke', type=int); q.add_argument('label'); q.add_argument('--tags')
    sub.add_parser('build')
    args = p.parse_args()
    {'sheet': cmd_sheet, 'wet': cmd_wet, 'dry': cmd_dry, 'label': cmd_label, 'build': lambda _a: build()}[args.cmd](args)


if __name__ == '__main__':
    main()
