import {afterEach,expect,it,vi} from 'vitest'
import {frontSharedTileShader,frontSharedTileGeometry} from './frontSharedTile'
import {CANONICAL_FACTOR_CACHED_WATER_FRONT_WGSL,CANONICAL_WATER_FRONT_WGSL} from './kernels'
import {CanonicalFieldPasses} from './dispatcher'
import {CanonicalStaticFrontCache} from './staticFrontCache'
import type {CanonicalGpuContext,CanonicalGpuField,CanonicalPassResources} from '../types'
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()})
function fixture(){vi.stubGlobal('GPUTextureUsage',{TEXTURE_BINDING:4,STORAGE_BINDING:8});vi.stubGlobal('GPUBufferUsage',{UNIFORM:4,COPY_DST:2});const uniform={destroy:vi.fn()},pass={setPipeline:vi.fn(),setBindGroup:vi.fn(),dispatchWorkgroups:vi.fn(),end:vi.fn()},begin=vi.fn(()=>pass),module=vi.fn((_descriptor:GPUShaderModuleDescriptor)=>({})),pipeline=vi.fn(()=>({getBindGroupLayout:()=>({})})),bind=vi.fn((_d:GPUBindGroupDescriptor)=>({}));const device={lost:new Promise(()=>{}),createBuffer:vi.fn(()=>uniform),createShaderModule:module,createComputePipeline:pipeline,createBindGroup:bind,queue:{writeBuffer:vi.fn()}} as unknown as GPUDevice;const field=(label:string,w=13,h=7)=>({width:w,height:h,format:'rgba8unorm',filter:'nearest',texture:{usage:12},view:{label},label} as CanonicalGpuField),a=field('a'),out=field('out'),resources={a,b:a,out,coverage:field('coverage'),paper:{field:field('paper',2048,2048),origin:[3,-4],texSize:[2048,2048],scale:1,staticInputEpoch:'fixture'},world:{x:0,y:0,width:13,height:7}} as CanonicalPassResources,noise=field('noise',251,251),ctx={device,encoder:{beginComputePass:begin}} as unknown as CanonicalGpuContext;const cache=vi.spyOn(CanonicalStaticFrontCache.prototype,'getOrEncode').mockReturnValue({} as GPUTextureView),p=new CanonicalFieldPasses(device),params={dryCost:2,costMax:8,climb:15,floor:1,stride:1,diagnosticStaticCache:true,diagnosticStaticCacheFactor:true,diagnosticSharedTileOwner:{ownsLiveField:()=>true}};return{p,ctx,resources,noise,params,pass,begin,module,pipeline,bind,cache,uniform}}
it('strict transform retains original UV bounds/8neighbor film/output and factor multiplication',()=>{const code=frontSharedTileShader(CANONICAL_FACTOR_CACHED_WATER_FRONT_WGSL);expect(code.indexOf('workgroupBarrier()')).toBeLessThan(code.indexOf('return;'));for(const anchor of ['let uv=px/u.resolution;','for(var k=0;k<8;k++)','let uvj=uv+o*stride/u.resolution;','if(any(uvj<vec2f(0))||any(uvj>vec2f(1))){continue;}','if(ci>=0.999){continue;}','climb=u.coefficients.x*cacheTile[center].g;','let film=smoothstep(0.02,0.15,max(fieldAt(coverage,uv).a,u.wet.y*fieldLinear(foreignFilm,uv).r));','vec4f(min(best,u.coefficients.z)/u.coefficients.z,hj,source.b,1)'])expect(code).toContain(anchor);expect(()=>frontSharedTileShader(CANONICAL_WATER_FRONT_WGSL)).toThrow('factor-cache');expect(()=>frontSharedTileShader(CANONICAL_FACTOR_CACHED_WATER_FRONT_WGSL.replace('let ci=','var ci='))).toThrow('anchor changed')})
it('actual compiled variant separated from original factor row, encoded count/stride stable and unreturned uniforms retained',()=>{const f=fixture();for(const stride of [1,2,4])expect(f.p.waterFront(f.ctx,f.resources,f.noise,{...f.params,stride})).toBe(f.uniform);expect(f.pipeline).toHaveBeenCalledTimes(2);expect(f.p.sharedTileVariantDiagnostics).toEqual([{code:frontSharedTileShader(CANONICAL_FACTOR_CACHED_WATER_FRONT_WGSL),encoded:2,stride1:1,stride2:1}]);expect(f.p.factorVariantDiagnostics.map(x=>x.encoded).sort()).toEqual([1,2]);expect(f.pass.dispatchWorkgroups).toHaveBeenCalledWith(2,1);expect(f.uniform.destroy).not.toHaveBeenCalled();expect(f.cache).toHaveBeenCalledTimes(3)})
it('OFF/cachemiss/film/source sampling/unsupported stride/DIM/deadowner cannot select shared shader',()=>{for(const change of [{diagnosticSharedTileOwner:undefined},{diagnosticFilmHoist:true},{diagnosticSourceFilter:'manual' as const},{stride:4},{diagnosticSharedTileOwner:{ownsLiveField:()=>false}}]){const f=fixture();f.p.waterFront(f.ctx,f.resources,f.noise,{...f.params,...change});expect(f.p.sharedTileVariantDiagnostics).toEqual([])}const f=fixture();f.cache.mockReturnValue(null);f.p.waterFront(f.ctx,f.resources,f.noise,f.params);expect(f.p.sharedTileVariantDiagnostics).toEqual([]);expect(frontSharedTileGeometry({...f.resources.a,width:8},f.resources.out,1)).toBe(false);expect(frontSharedTileGeometry({...f.resources.a,filter:'linear'},f.resources.out,1)).toBe(false)})
it('alias/finite guards precede cache; binding/end failures destroy uniform without successful variant counts',()=>{const a=fixture();expect(()=>a.p.waterFront(a.ctx,{...a.resources,out:a.resources.a},a.noise,a.params)).toThrow('aliases');expect(a.cache).not.toHaveBeenCalled();expect(()=>a.p.waterFront(a.ctx,a.resources,a.noise,{...a.params,climb:NaN})).toThrow('finite');expect(a.cache).not.toHaveBeenCalled();for(const stage of ['bind','end']){const f=fixture();(stage==='bind'?f.bind:f.pass.end).mockImplementation(()=>{throw Error(stage+' fail')});expect(()=>f.p.waterFront(f.ctx,f.resources,f.noise,f.params)).toThrow(stage+' fail');expect(f.uniform.destroy).toHaveBeenCalledTimes(1);expect(f.p.sharedTileVariantDiagnostics[0].encoded).toBe(0)}})
