import {afterEach,expect,it,vi} from 'vitest'
import {CanonicalFieldOps,CANONICAL_FIELD_OPS_WGSL} from './fieldOps'
import {canonicalMode5TileRecipe,MODE5_TILE_DIMENSIONS,mode5TileGeometry} from './mode5Tile'
import type {CanonicalGpuContext,CanonicalGpuField,CanonicalPassResources} from '../types'
afterEach(()=>vi.unstubAllGlobals())
function fixture(){vi.stubGlobal('GPUTextureUsage',{TEXTURE_BINDING:4,STORAGE_BINDING:8});vi.stubGlobal('GPUBufferUsage',{UNIFORM:4,COPY_DST:2});const uniform={destroy:vi.fn()},pass={setPipeline:vi.fn(),setBindGroup:vi.fn(),dispatchWorkgroups:vi.fn(),end:vi.fn()},begin=vi.fn(()=>pass),module=vi.fn(()=>({})),bind=vi.fn((_descriptor:GPUBindGroupDescriptor)=>({})),pipeline=vi.fn(()=>({getBindGroupLayout:()=>({})}));const device={createBuffer:vi.fn(()=>uniform),createShaderModule:module,createComputePipeline:pipeline,createBindGroup:bind,queue:{writeBuffer:vi.fn()}} as unknown as GPUDevice;const field=(label:string)=>({width:13,height:7,filter:'nearest',format:'rgba8unorm',texture:{usage:12},view:{label},label} as CanonicalGpuField),a=field('a'),b=field('b'),out=field('out'),r={a,b,out,coverage:a,paper:{},world:{x:0,y:0,width:13,height:7}} as CanonicalPassResources,ctx={device,encoder:{beginComputePass:begin}} as unknown as CanonicalGpuContext;return{ops:new CanonicalFieldOps(device),r,ctx,uniform,pass,begin,module,bind,pipeline,owner:{ownsLiveField:()=>true}}}
it('reuses actual baseline128B struct, barrier precedes all early returns and sums preserve j/i order',()=>{const recipe=canonicalMode5TileRecipe(CANONICAL_FIELD_OPS_WGSL);expect(recipe.code.split('\n')[0]).toBe(CANONICAL_FIELD_OPS_WGSL.match(/struct Params \{[^\n]+\}/)![0]);expect(recipe.code.indexOf('workgroupBarrier()')).toBeLessThan(recipe.code.indexOf('return;'));expect(recipe.code).toContain('s+=wx*wy*tile[index]');expect(recipe.code).toContain('s/16.0');expect(()=>canonicalMode5TileRecipe('wrong')).toThrow('uniform contract')})
it('DIM whitelist and stride guards reject unsupported nearest coordinate domains',()=>{const f=fixture();for(const n of MODE5_TILE_DIMENSIONS){const a={...f.r.a,width:n,height:n},out={...f.r.out,width:n,height:n};expect(mode5TileGeometry(out,a,[1,1],0)).toBe(true);expect(mode5TileGeometry(out,a,[2,2],0)).toBe(true);for(const s of [1,2])expect(Math.round(Math.fround(Math.fround(s/n)*n))).toBe(s)}for(const change of [{width:8},{filter:'linear'},{format:'r32float'}])expect(mode5TileGeometry(f.r.out,{...f.r.a,...change} as CanonicalGpuField,[1,1],0)).toBe(false);expect(mode5TileGeometry(f.r.out,f.r.a,[4,4],0)).toBe(false);expect(mode5TileGeometry(f.r.out,f.r.a,[1,2],0)).toBe(false);expect(mode5TileGeometry(f.r.out,f.r.a,[1,1],1)).toBe(false)})
it('actual pipeline/binding/dispatch uses sameuniform128/rect and keeps uniform until caller ACK',()=>{const f=fixture();for(const stride of [1,2])expect(f.ops.run(f.ctx,f.r,5,0,{dir:[stride,stride],scissor:[1,1,9,5],diagnosticMode5TileOwner:f.owner})).toBe(f.uniform);expect(f.pipeline).toHaveBeenCalledTimes(1);expect(f.module).toHaveBeenCalledTimes(1);expect(f.begin).toHaveBeenCalledWith({label:'Canonical mode5 shared tile'});expect(Array.from(f.bind.mock.calls[0]![0].entries).map(x=>x.binding)).toEqual([0,7,8]);expect(f.pass.dispatchWorkgroups).toHaveBeenCalledWith(2,1);expect(f.uniform.destroy).not.toHaveBeenCalled();expect(f.ops.mode5TileDiagnostics?.encoded).toBe(2);expect(f.ops.mode5TileDiagnostics?.code).toBe(canonicalMode5TileRecipe(CANONICAL_FIELD_OPS_WGSL).code)})
it('OFF/unsupported geometry/deadowner retains baseline branch; all old alias/finite errors precede variant',()=>{for(const options of [{dir:[1,1] as const},{dir:[4,4] as const,diagnosticMode5TileOwner:{ownsLiveField:()=>true}},{dir:[1,1] as const,diagnosticMode5TileOwner:{ownsLiveField:()=>false}}]){const f=fixture();f.ops.run(f.ctx,f.r,5,0,options);expect(f.begin).toHaveBeenCalledWith({label:'Canonical fieldOp 5'});expect(f.ops.mode5TileDiagnostics).toBeNull()}for(const o of [{dir:[NaN,1] as const},{linearInputMask:64},{c:'alias'}]){const f=fixture();const options:any={dir:[1,1],diagnosticMode5TileOwner:f.owner,...o};if(o.c)options.c=f.r.out;expect(()=>f.ops.run(f.ctx,f.r,5,0,options)).toThrow();expect(f.module).not.toHaveBeenCalled()}})

it('failed binding or pass end destroys unreturned uniform and does not count consumed variant',()=>{for(const stage of ['bind','end']){const f=fixture();(stage==='bind'?f.bind:f.pass.end).mockImplementation(()=>{throw Error(stage+' failure')});expect(()=>f.ops.run(f.ctx,f.r,5,0,{dir:[1,1],diagnosticMode5TileOwner:f.owner})).toThrow(stage+' failure');expect(f.uniform.destroy).toHaveBeenCalledTimes(1);expect(f.ops.mode5TileDiagnostics?.encoded).toBe(0)}})
