import {momentVectorGpuOracle} from '../../../../apps/web/src/engine/src/experiments/wetBrushMomentVectorGpu'
import {packMomentRecords,momentGpuOracle} from '../../../../apps/web/src/engine/src/experiments/wetBrushMomentGpu'
export function expectedMomentTexture(p:Uint8Array,c:Uint8Array,width:number,rect:{x:number;y:number;width:number;height:number},recipe:{mixRate:number;advectionRate:number;directionX:number;directionY:number},invalidFixture=false,diagnosticVector=false){
 let expectedP=p,expectedC=c;if(!invalidFixture||diagnosticVector){
 const crop=(bytes:Uint8Array)=>{const out=new Uint8Array(rect.width*rect.height*4);for(let row=0;row<rect.height;row++)out.set(bytes.subarray(((rect.y+row)*width+rect.x)*4,((rect.y+row)*width+rect.x+rect.width)*4),row*rect.width*4);return out}
 let oracle:Uint32Array;if(diagnosticVector){const pp=crop(p),cc=crop(c);oracle=new Uint32Array(rect.width*rect.height*10);for(let i=0;i<pp.length/4;i++){oracle.set(pp.subarray(i*4,i*4+4),i*10);oracle.set(cc.subarray(i*4,i*4+4),i*10+4);oracle[i*10+8]=255;oracle[i*10+9]=255}}else oracle=packMomentRecords(crop(p),crop(c),new Uint8Array(rect.width*rect.height).fill(255),new Uint8Array(rect.width*rect.height).fill(255));for(const axis of [0,1] as const)for(const parity of [0,1] as const)oracle=(diagnosticVector?momentVectorGpuOracle:momentGpuOracle)(oracle,{width:rect.width,height:rect.height,axis,parity,mixRate:recipe.mixRate,advectionRate:recipe.advectionRate,direction:axis===0?recipe.directionX:recipe.directionY});expectedP=p.slice();expectedC=c.slice();for(let i=0;i<rect.width*rect.height;i++){const offset=((rect.y+Math.floor(i/rect.width))*width+rect.x+i%rect.width)*4;expectedP.set(oracle.subarray(i*10,i*10+4),offset);expectedC.set(oracle.subarray(i*10+4,i*10+8),offset)}}

 return {expectedP,expectedC}
}
