/// <reference types="@webgpu/types" />
import {WetBrushMomentTextureOwner} from '../../../../apps/web/src/engine/src/experiments/wetBrushMomentTextureOwner'
import {momentVectorGpuOracle} from '../../../../apps/web/src/engine/src/experiments/wetBrushMomentVectorGpu'
import {expectedMomentTexture} from './moment-texture-oracle'
/** Small actual canonical format gate; zero-rate arm proves pack/unpack fidelity. */
export async function runMomentTextureGate(transport=false,invalidFixture=false,diagnosticInPlace=false,partialRoi=false,diagnosticVector=false,zeroCarrierFixture=false,stageCapture=false){
 if(!navigator.gpu)throw Error('WebGPU required');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('Adapter unavailable');const device=await adapter.requestDevice(),owned:(GPUTexture|GPUBuffer)[]=[],errors:string[]=[]
 device.addEventListener('uncapturederror',e=>errors.push(e.error.message));const width=17,height=13,n=width*height,p=new Uint8Array(n*4),c=p.slice(),wet=p.slice(),contact=p.slice()
 for(let i=0;i<n;i++){p.set([i%256,200,100,220],i*4);c.set([i%2?90:10,30,20,100],i*4);wet.set([0,0,255,255],i*4);contact.set([0,0,0,255],i*4)}if(zeroCarrierFixture){if(!diagnosticVector)throw Error('Zero independent carriers require vector contract');for(let i=0;i<n;i++){p[i*4+2]=0;c[i*4+3]=0}}
 const rect=partialRoi?{x:2,y:2,width:11,height:7}:{x:0,y:0,width,height};if(invalidFixture){const offset=(rect.y*width+rect.x)*4;if(diagnosticVector){p.set([255,255,170,255],offset);c.set([80,180,60,200],offset)}else c[offset]=101}
 try{const texture=(bytes?:Uint8Array)=>{const t=device.createTexture({size:[width,height],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST});owned.push(t);if(bytes)device.queue.writeTexture({texture:t},bytes as Uint8Array<ArrayBuffer>,{bytesPerRow:width*4},[width,height]);return t},pt=texture(p),ct=texture(c),wt=texture(wet),touch=texture(contact),po=diagnosticInPlace?pt:texture(),co=diagnosticInPlace?ct:texture(),owner=new WetBrushMomentTextureOwner(device,diagnosticVector),encoder=device.createCommandEncoder()
 const recipe={ordinal:0,x256:0,y256:0,radius256:256,pressure256:256,directionX:256,directionY:-256,mixRate:transport?48:0,advectionRate:transport?80:0}
 const result=owner.encode(encoder,{pigment:pt,color:ct,availableWater:wt,contact:touch,outputPigment:po,outputColor:co,rect,recipe,diagnosticInPlace,...(stageCapture?{diagnosticStages:{x:0,y:0,width:rect.width,height:rect.height}}:{})},true);owned.push(...result.buffers)
 const read=device.createBuffer({size:256*height*2+4,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});owned.push(read);encoder.copyTextureToBuffer({texture:po},{buffer:read,bytesPerRow:256},[width,height]);encoder.copyTextureToBuffer({texture:co},{buffer:read,offset:256*height,bytesPerRow:256},[width,height]);encoder.copyBufferToBuffer(result.invalid!,0,read,256*height*2,4);device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const bytes=new Uint8Array(read.getMappedRange().slice(0)),actualP=p.slice(),actualC=c.slice();for(let y=0;y<height;y++){actualP.set(bytes.subarray(y*256,y*256+width*4),y*width*4);actualC.set(bytes.subarray(256*height+y*256,256*height+y*256+width*4),y*width*4)}const invalid=new Uint32Array(bytes.buffer,256*height*2,1)[0];read.unmap()
 const stages:{stage:string;sha:string;differences:number;maxDifference:number}[]=[]
 if(stageCapture){if(!diagnosticVector)throw Error('Stage fixture requires vector contract');let records=new Uint32Array(rect.width*rect.height*10);for(let y=0;y<rect.height;y++)for(let x=0;x<rect.width;x++){const i=(y*rect.width+x)*10,k=((y+rect.y)*width+x+rect.x)*4;records.set(p.subarray(k,k+4),i);records.set(c.subarray(k,k+4),i+4);records[i+8]=255;records[i+9]=255}
 for(const stage of result.stages??[]){if(stage.stage.startsWith('pair-')){const [,axis,parity]=stage.stage.split('-').map(Number);records=momentVectorGpuOracle(records,{width:rect.width,height:rect.height,axis:axis as 0|1,parity:parity as 0|1,mixRate:recipe.mixRate,advectionRate:recipe.advectionRate,direction:axis===0?recipe.directionX:recipe.directionY}) as Uint32Array<ArrayBuffer>}
 await stage.buffer.mapAsync(GPUMapMode.READ);const raw=new Uint8Array(stage.buffer.getMappedRange().slice(0));stage.buffer.unmap();const tight=new Uint8Array(stage.width*stage.height*stage.bytesPerRecord),stride=stage.bytesPerRow??stage.width*stage.bytesPerRecord;for(let row=0;row<stage.height;row++)tight.set(raw.subarray(row*stride,row*stride+stage.width*stage.bytesPerRecord),row*stage.width*stage.bytesPerRecord);const actual=stage.bytesPerRecord===40?new Uint32Array(tight.buffer):tight,expected=stage.bytesPerRecord===40?records:new Uint8Array(Array.from({length:stage.width*stage.height*4},(_,i)=>records[Math.floor(i/4)*10+(stage.stage==='unpack-P'?0:4)+i%4]));let differences=0,maxDifference=0;actual.forEach((v,i)=>{const d=Math.abs(v-expected[i]);if(d){differences++;maxDifference=Math.max(maxDifference,d)}});const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',actual.buffer)),x=>x.toString(16).padStart(2,'0')).join('');stages.push({stage:stage.stage,sha,differences,maxDifference})}
 }
 const {expectedP,expectedC}=expectedMomentTexture(p,c,width,rect,recipe,invalidFixture,diagnosticVector)

 let differences=0,maxDifference=0;for(const [actual,expected]of [[actualP,expectedP],[actualC,expectedC]])for(let i=0;i<actual.length;i++){const delta=Math.abs(actual[i]-expected[i]);if(delta){differences++;maxDifference=Math.max(maxDifference,delta)}}const sums=(bytes:Uint8Array)=>[0,1,2,3].map(k=>bytes.reduce((sum,v,i)=>sum+(i%4===k?v:0),0));const channels={beforeP:sums(p),beforeC:sums(c),afterP:sums(actualP),afterC:sums(actualC)};let outsideDifferences=0;for(let i=0;i<n;i++){const x=i%width,y=Math.floor(i/width);if(x<rect.x||x>=rect.x+rect.width||y<rect.y||y>=rect.y+rect.height)for(let k=0;k<4;k++)outsideDifferences+=Number(actualP[i*4+k]!==p[i*4+k])+Number(actualC[i*4+k]!==c[i*4+k])}return{stages,channels,outsideDifferences,valid:stages.every(s=>s.differences===0)&&differences===0&&errors.length===0&&(invalidFixture&&!diagnosticVector?invalid===1:invalid===0),transport,invalidFixture,diagnosticInPlace,partialRoi,diagnosticVector,zeroCarrierFixture,fixtureMeaning:diagnosticVector&&invalidFixture?'Supported source-fit PB170/CG180/CA200, not invalid carrier':invalidFixture?'Legacy C<=PB violation':zeroCarrierFixture?'Supported zero-PB/zero-CA positive optical RGB':'Normal',invalidChannels:invalid,differences,maxDifference,errors,limitations:['Synthetic actual RGBA8 format gate','Not an actual Room scene or naturalness judgment','No hardware performance claim']}
 }finally{for(const r of owned)r.destroy();device.destroy()}
}
