/// <reference types="@webgpu/types" />
import {makeWetBrushState,depositWetBrush,exchangeWetBrush,wetBrushMass,wetBrushMetrics,WET_BRUSH_TRANSPORT_WGSL,type WetBrushState,type TransportPass} from '../../../../apps/web/src/engine/src/experiments/wetBrushTransport'
const N=128,R=25, dose=180
const corners=[[300,300],[600,300],[600,500],[300,500],[300,700],[600,700]]
function tape(){const points=[corners[0]];for(let i=1;i<corners.length;i++){const [x,y]=corners[i-1],[tx,ty]=corners[i],n=Math.ceil(Math.hypot(tx-x,ty-y)/20);for(let j=1;j<=n;j++)points.push([x+(tx-x)*j/n,y+(ty-y)*j/n])}return points}
const depositShader=`struct Params{n:u32,pad:vec3u}\n@group(0) @binding(0) var<storage,read_write> mass:array<vec2u>;@group(0) @binding(1) var<storage,read> dose:array<vec2u>;@group(0) @binding(2) var<uniform> p:Params;@compute @workgroup_size(64) fn main(@builtin(global_invocation_id) id:vec3u){if(id.x>=p.n){return;}mass[id.x]=min(vec2u(65535u),mass[id.x]+dose[id.x]);}`
class GpuTransport {
 device:GPUDevice;mass:GPUBuffer[];wet:GPUBuffer;dose:GPUBuffer;pass:GPUComputePipeline;deposit:GPUComputePipeline;index=0
 constructor(device:GPUDevice){this.device=device;const create=(bytes:number,uniform=false)=>device.createBuffer({size:bytes,usage:uniform?GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST|GPUBufferUsage.COPY_SRC});this.mass=[create(N*N*8),create(N*N*8)];this.wet=create(N*N*8);this.dose=create(N*N*8);this.pass=device.createComputePipeline({layout:'auto',compute:{module:device.createShaderModule({code:WET_BRUSH_TRANSPORT_WGSL}),entryPoint:'main'}});this.deposit=device.createComputePipeline({layout:'auto',compute:{module:device.createShaderModule({code:depositShader}),entryPoint:'main'}})}
 step(contact:WetBrushState,delta:Uint32Array,passes:TransportPass[]){const d=this.device,wet=new Uint32Array(N*N*2);for(let i=0;i<N*N;i++){wet[i*2]=contact.water[i];wet[i*2+1]=contact.contact[i]}d.queue.writeBuffer(this.wet,0,wet);d.queue.writeBuffer(this.dose,0,delta);const encoder=d.createCommandEncoder(),transient:GPUBuffer[]=[]
 const uniform=(data:Uint32Array)=>{const b=d.createBuffer({size:32,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});d.queue.writeBuffer(b,0,data);transient.push(b);return b}
 const emit=(pipeline:GPUComputePipeline,entries:GPUBindGroupEntry[])=>{const p=encoder.beginComputePass();p.setPipeline(pipeline);p.setBindGroup(0,d.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries}));p.dispatchWorkgroups(Math.ceil(N*N/64));p.end()}
 emit(this.deposit,[{binding:0,resource:{buffer:this.mass[this.index]}},{binding:1,resource:{buffer:this.dose}},{binding:2,resource:{buffer:uniform(new Uint32Array([N*N,0,0,0,0,0,0,0]))}}])
 for(const p of passes){const next=1-this.index,params=new Uint32Array([N,N,p.axis,p.parity,p.mixRate,p.advectionRate,p.direction>>>0,0]);emit(this.pass,[{binding:0,resource:{buffer:this.mass[this.index]}},{binding:1,resource:{buffer:this.mass[next]}},{binding:2,resource:{buffer:this.wet}},{binding:3,resource:{buffer:uniform(params)}}]);this.index=next}d.queue.submit([encoder.finish()]);return d.queue.onSubmittedWorkDone().then(()=>{for(const b of transient)b.destroy()})}
 async read(){const b=this.device.createBuffer({size:N*N*8,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ}),e=this.device.createCommandEncoder();e.copyBufferToBuffer(this.mass[this.index],0,b,0,N*N*8);this.device.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const out=new Uint32Array(b.getMappedRange().slice(0));b.unmap();b.destroy();return out}
 destroy(){for(const b of [...this.mass,this.wet,this.dose])b.destroy();this.device.destroy()}
}
function draw(canvas:HTMLCanvasElement,s:WetBrushState){canvas.width=canvas.height=N;const ctx=canvas.getContext('2d')!,image=ctx.createImageData(N,N);for(let n=0;n<N*N;n++){const a=1-Math.exp(-(s.mass[n*2]+s.mass[n*2+1])/2400),green=s.mass[n*2+1]/Math.max(1,s.mass[n*2]+s.mass[n*2+1]);image.data.set([Math.round(250*(1-a)+a*(65+green*25)),Math.round(249*(1-a)+a*green*115),Math.round(247*(1-a)+a*(160-green*120)),255],n*4)}ctx.putImageData(image,0,0)}
export async function runWetTransport(scene:'zigzag'|'unified',transport=true){if(!navigator.gpu)throw Error('WebGPU unavailable; hardware not validated');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('WebGPU adapter unavailable');const device=await adapter.requestDevice(),gpu=new GpuTransport(device),errors:string[]=[];device.addEventListener('uncapturederror',e=>errors.push(e.error.message));const reference=makeWetBrushState(N,N),oracle=makeWetBrushState(N,N),points=tape(),expected=[0,0];let before=points[0];try{
 // Prior water is SAME function/dose, simply earlier in time. It has no pigment.
 if(scene==='unified')for(const [x,y]of points)depositWetBrush(oracle,x/8,y/8,R,65535,[0,0])
 let step=0;for(const [x,y]of points){const green=step>points.length/2,pigment:[number,number]=green?[0,dose]:[dose,0],delta=new Uint32Array(N*N*2);const old=oracle.mass.slice(),added=depositWetBrush(oracle,x/8,y/8,R,65535,pigment);for(let i=0;i<delta.length;i++)delta[i]=oracle.mass[i]-old[i];expected[0]+=added[0];expected[1]+=added[1];depositWetBrush(reference,x/8,y/8,R,65535,pigment)
 const dx=x-before[0],dy=y-before[1],length=Math.hypot(dx,dy),direction=[length?Math.round(dx/length*256):0,length?Math.round(dy/length*256):0],passes:TransportPass[]=transport?[{axis:0,parity:(step%2) as 0|1,mixRate:48,advectionRate:80,direction:direction[0]},{axis:1,parity:(step%2) as 0|1,mixRate:48,advectionRate:80,direction:direction[1]},{axis:0,parity:((step+1)%2) as 0|1,mixRate:48,advectionRate:80,direction:direction[0]},{axis:1,parity:((step+1)%2) as 0|1,mixRate:48,advectionRate:80,direction:direction[1]}]:[]
 for(const p of passes)exchangeWetBrush(oracle,p);await gpu.step(oracle,delta,passes);before=[x,y];step++}
 const bytes=await gpu.read(),exact=bytes.every((v,i)=>v===oracle.mass[i]);oracle.mass=bytes;draw(document.querySelector('#reference')!,reference);draw(document.querySelector('#candidate')!,oracle);return{scene,transport,newModel:true,canonical:false,grid:N,brushWorldPx:400,tapePoints:points.length,expectedMass:expected,actualMass:wetBrushMass(oracle),metrics:{reference:wetBrushMetrics(reference),candidate:wetBrushMetrics(oracle)},massExact:expected.every((v,i)=>v===wetBrushMass(oracle)[i]),gpuVsCpuExact:exact,errors,limitations:['Integer new-operator prototype, NOT Grafetto watercolor integration','Per-step queue completion ensures small fixture lifetime, NOT performance','No baked-paper/tide/drying solver; image is simple tracer presentation','Prior water and combined water use same deposition; differing wet timing may yield different images','Hardware picture quality unreviewed']}}finally{gpu.destroy()}}
const button=document.querySelector<HTMLButtonElement>('#run');button?.addEventListener('click',async()=>{button.disabled=true;try{document.querySelector('#status')!.textContent=JSON.stringify(await runWetTransport((document.querySelector<HTMLSelectElement>('#scene')!.value) as 'zigzag'|'unified',document.querySelector<HTMLInputElement>('#on')!.checked),null,2)}catch(e){document.querySelector('#status')!.textContent=String(e)}finally{button.disabled=false}})

export {runMomentGate} from "./moment-gate"

export {runMomentTextureGate} from "./moment-texture-gate"
