import {it,expect,vi} from 'vitest'
import {CanonicalPlanAdapter} from './settlePlanAdapter'
function fixture(){const live=new Set(),owner={ownsLiveField:(f:unknown)=>live.has(f)},buffer=()=>{const field={texture:{},view:{},width:16,height:16,format:'rgba8unorm',filter:'nearest'};live.add(field);return{owner,field,width:16,height:16,filter:'nearest',destroyed:false,get texture(){return field.texture}}},p=buffer(),c=buffer(),w=buffer(),op=buffer(),oc=buffer(),flow={field:buffer().field,destroyed:false},encode=vi.fn(()=>['retained']),adapter=Object.create(CanonicalPlanAdapter.prototype) as CanonicalPlanAdapter;Object.assign(adapter,{owner,brush:{encode},context:{},transient:[],diagnosticNativeBrushPair:false,pairedBrushCalls:0});return{adapter,p,c,w,op,oc,flow,encode,live,args:[{w:16,h:16,coverage:w},flow,8,1,p,op,c,oc,[0,0,1,1],[0,0,16,16],.5] as unknown as Parameters<CanonicalPlanAdapter['brushPair']>}}
it('OFF leaves original two-pass planner and resources untouched; ON returns exact paired old inputs',()=>{const f=fixture();expect(f.adapter.brushPair(...f.args)).toBe(false);expect(f.encode).not.toHaveBeenCalled();f.adapter.diagnosticNativeBrushPair=true;expect(f.adapter.brushPair(...f.args)).toBe(true);expect(f.encode).toHaveBeenCalledExactlyOnceWith({}, {pigment:f.p.field,color:f.c.field,flow:f.flow.field,water:f.w.field,outPigment:f.op.field,outColor:f.oc.field},[2/16,2/16],.5,[0,0,1,1],[0,0,16,16]);expect(f.adapter.pairedBrushCalls).toBe(1)})
it('paired admission rejects stale, foreign, aliases, dimensions, format and scalars before encode',()=>{for(const change of [(f:ReturnType<typeof fixture>)=>f.live.delete(f.p.field),f=>f.op.destroyed=true,f=>f.op.field.texture=f.p.field.texture,f=>f.oc.field.texture=f.op.field.texture,f=>f.op.width=8,f=>f.w.field.format='r8unorm',f=>f.args[2]=NaN,f=>f.args[9]=[0,0,17,16]]){const f=fixture();f.adapter.diagnosticNativeBrushPair=true;change(f);expect(()=>f.adapter.brushPair(...f.args)).toThrow();expect(f.encode).not.toHaveBeenCalled()}})
it('failed original paired encoding never claims accepted pulse',()=>{const f=fixture();f.adapter.diagnosticNativeBrushPair=true;f.encode.mockImplementation(()=>{throw Error('encode failed')});expect(()=>f.adapter.brushPair(...f.args)).toThrow('encode failed');expect(f.adapter.pairedBrushCalls).toBe(0)})

import {assertNativeBrushPairOptions} from './nativeBrushPairOptions'
it('direct constructor option guard rejects deferred/mixed before GPU initialization, OFF unchanged',()=>{for(const options of [{joinedFinishDeferred:true},{joinedTouchMixed:true},{diagnosticBrushMrt:true}]){expect(()=>assertNativeBrushPairOptions(true,true,options)).toThrow();expect(()=>assertNativeBrushPairOptions(false,true,options)).not.toThrow()}expect(()=>assertNativeBrushPairOptions(true,true,{})).not.toThrow();expect(()=>assertNativeBrushPairOptions(true,false,{})).toThrow()})
