import{expect,it,vi}from'vitest'
const shared=vi.hoisted(()=>({current:null as any,calls:[]as string[]}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/temp/owner-fifo-runtime/OwnerRibbonStrokePainter.ts',()=>({RibbonStrokePainter:class{diagnosticSegmented='combined';*paint(...args:any[]){const scratch=args[6],mode=args[12];scratch.diffusePending=true;mode.deferMaterial({metadata:{gesture:scratch.gesture},typedSource:{foreignImport:{enabled:false,dabs:[]},commands:[],rect:[0,0,1,1],composite:{bounds:{minX:0,minY:0,maxX:1,maxY:1},profile:{normalizeDeposit:true},preset:{hardness:1}}},cancel:()=>{}})}}}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/PrewarmedGlOwnerPool.ts',()=>({PrewarmedGlOwnerPool:class{bytes=156*1024*1024;physicalIdentities=new Set<object>();free=3;next=0;closeLostGeneration(){shared.calls.push('close-lost');this.free=0}destroyLostGeneration(){shared.calls.push('destroy-lost')}take(){if(!this.free)return null;this.free--;const fields=Object.fromEntries(['presentation','original','coverage','coverageFilm','pigmentLoad','pigmentBase','pigmentFilm','colourLoad','colourBase','colourFilm','solventLoad','solventBase','solventFilm'].map(role=>[role,{width:1024,height:1024,texture:{id:++this.next},version:0,copyTo(out:any){out.version=this.version;if(role==='presentation')shared.calls.push('copy-visible-to-reveal')}}]));let used=false;return{fields,bytes:52*1024*1024,resources:Object.entries(fields).map(([role,f]:any)=>({identity:f.texture,role:role==='presentation'?'presentation':'canonical-source',width:1024,height:1024})),release:()=>{if(!used){used=true;this.free++}}}}disposeAfterFence(){if(this.free!==3)throw Error('active leases')}}}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/OwnedGlPreparedSource.ts',()=>({OwnedGlPreparedSource:class{private lease:any;epoch=0;rebaseToken:any;constructor(input:any){this.lease=input.lease;this.rebaseToken=input.ownerToken?Object.freeze({...input.ownerToken}):null}paint(){shared.calls.push('visible-source')}rebaseFromPredecessor(input:any){expect(input.ownerToken).toBe(this.rebaseToken);expect(input.expectedEpoch).toBe(this.epoch);expect(input.predecessorGesture).toBeLessThan(this.rebaseToken.gesture);shared.calls.push('material-rebase:'+this.rebaseToken.gesture+':'+input.fields.pigmentLoad.version);this.lease.fields.pigmentLoad.version=input.fields.pigmentLoad.version;this.epoch=input.nextEpoch}retire(){this.lease.release()}}}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/TypedGlSourceReplayPrototype.ts',()=>({TypedGlSourceReplayPrototype:class{constructor(private input:any){}execute(port:any){const binding=port.bindCurrentCanonical();expect(binding.landedVersion).toBe(this.input.expectedPredecessorVersion);shared.calls.push('canonical-base:'+binding.fields.pigmentLoad.version)}}}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/PreparedGlSourceDraw.ts',()=>({createPreparedGlSourcePort:(input:any)=>({bindCurrentCanonical:input.bindCurrentCanonical})}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/OwnedPreviewRuntime.mjs',()=>({createOwnedPreviewRuntime:async(e:any,morph:any)=>{const active=new Set<any>(),retired=new Set<any>();return{bytes:13762560,get freeSlots(){return 3-active.size-retired.size},seal(o:any){active.add(o)},beforeRebase(o:any){if(active.has(o)){e.gl.copyTexSubImage2D();shared.calls.push('preview-copy');active.delete(o);retired.add(o)}},retire(o:any){if(active.delete(o))retired.add(o);shared.calls.push('preview-retire')},releaseRetiredOwnerAfterKnownIdle(o:any){return retired.delete(o)},visibleField(o:any){return morph.visibleField(o)},ownsPending(){return false},handleContextLoss(){for(const o of active)retired.add(o);active.clear()},disposeAfterFence(){active.clear();retired.clear()}}}}))
import{installOwnerFifo}from'./generated-current-reuse-install.mjs'
import{watercolorWashSignature}from'/home/suselman/projects/pencil-agents/728-solvent-init/apps/web/src/engine/src/presets/watercolorPresets'
function fixture(options={}){
 const field=()=>({width:1024,height:1024,texture:{},version:0,copyTo(out:any){out.version=this.version}}),target={buffer:field(),originX:0,originY:0},entry={original:field(),coverage:field(),inkLoad:field(),inkColor:field(),solventLoad:field()};const requests:any[]=[]
 const scratch:any={gesture:0,tileEntries:()=>[][Symbol.iterator](),diffusePending:true,captureFinishMetadata:()=>({gesture:scratch.gesture}),captureCanonicalFinish:()=>{shared.calls.push('capture-canonical:'+scratch.diffusePending);const finish={gesture:scratch.gesture,diffusePending:scratch.diffusePending};scratch.diffusePending=false;return finish},activateMaterialFilm(){},getOrCreate:()=>entry,peek:()=>entry,filmBuffers:()=>({strokeInk:field(),inkBase:field(),strokeColor:field(),colorBase:field()}),runningCoverage(){},solventFilm:()=>({load:field(),base:field(),film:field()})};
 const listeners=new Map<string,()=>void>();
 const e:any={gl:{canvas:{addEventListener(k:string,f:()=>void){listeners.set(k,f)},removeEventListener(k:string){listeners.delete(k)}},isContextLost:()=>false,finish:vi.fn(),drawArrays:vi.fn(),copyTexSubImage2D:vi.fn(),copyTexImage2D:vi.fn(),clear:vi.fn(),readPixels:vi.fn()},_syncContinuationGpu(){e.gl.finish()},_pageSize:()=>({w:1024,h:1024}),_opts:{tool:'watercolor',pencilType:'normal:100:100',graphiteColor:[.2,.3,.4]},_activeId:'layer',_layers:new Map([['layer',{}]]),_ribbonStrokeScratch:scratch,_ribbonScratchPool:{acquire:()=>field(),release(){}},_ribbonPainter:{},_ribbonPainterContext:{resolveWithinSheet:()=>[target]},_minmaxExt:{},_washReveals:new Map(),_revealPool:[],_revealPoolAcquire(){return{width:1024,height:1024,texture:{}}},_revealPoolRelease(f:any){e._revealPool.push(f)},_advanceWashReveal(_buffer:any,reveal:any){reveal.before=field()},_fieldOp(){},_revealBeforeBatch(){shared.calls.push('visual-before');return null},_revealAfterBatch(){shared.calls.push('visual-after')},_revealHold:()=>1,_revealWash(tile:any){e._washReveals.set(tile.buffer,{before:field()})},_wcCanonical:{ctx:{blocked:()=>false},get pending(){return false},enqueue(request:any){requests.push(request)},cancel(lost:boolean){for(const r of requests)r.cancel(lost);requests.length=0}},_asyncLocalPreviewTiles:()=>new Map(),_holdAsyncScratch(){},_releaseAsyncScratch(){},_markPaperDamage(){},_invalidateSplitCache(){},_scheduleDisplay(){},_drawRibbonCompositeRect(){shared.calls.push('canonical-composite')},_ribbonStrokeWork(){throw Error('unexpected fallback')},_onStart(){scratch.gesture++;e._strokeLayerId='layer';e._wash={scratch,layerId:'layer',signature:watercolorWashSignature(e._opts.pencilType,e._opts.graphiteColor),endedAt:performance.now()};const work=e._ribbonStrokeWork({markContentPainted(){shared.calls.push('content-painted')}},[],{},'normal',{},[],scratch,undefined,undefined,undefined,true);while(!work.next().done){}},_finishRibbonStroke(_scratch:any,...args:any[]){if(args[3]){e._revealWash(target,{});e._washReveals.get(target.buffer).progressive=true;shared.calls.push('original-owned-finish');return}const finish=scratch.captureCanonicalFinish();e._wcCanonical.enqueue({execute:function*(){e._finishRibbonStroke(scratch,true,true,false,finish);entry.inkLoad.version++;yield 0},cancel(){}})}};
 const rawGl={...e.gl};const status=vi.fn(),owner=installOwnerFifo(e,{status,...options});e.__listeners=listeners;return{e,rawGl,owner,scratch,requests,status}
}
it('admits three without draining and old FIFO land keeps newest overlay; late base changes are observed',()=>{
 shared.calls=[];const {e,owner,scratch,requests,status}=fixture();
 for(let n=0;n<3;n++){e._onStart({});e._finishRibbonStroke(scratch);e._strokeLayerId=null}
 expect(owner.snapshot().owners).toHaveLength(3);expect(shared.calls.filter(x=>x==='visible-source')).toHaveLength(3);expect(shared.calls.filter(x=>x.startsWith('capture-canonical:'))).toHaveLength(3);expect(shared.calls.filter(x=>x.startsWith('capture-canonical:'))).toEqual(['capture-canonical:true','capture-canonical:true','capture-canonical:true']);e._onStart({});expect(scratch.gesture).toBe(3);expect(status).toHaveBeenLastCalledWith(expect.stringContaining('заполнена'))
 const latest=e._asyncLocalPreviewTiles().get('layer')[0].buffer;
 for(let n=0;n<2;n++){const work=requests.shift().execute();while(!work.next().done){}}
 expect(owner.snapshot().owners).toHaveLength(2);expect(e._asyncLocalPreviewTiles().get('layer')[0].buffer).toBe(latest)
 while(requests.length){const work=requests.shift().execute();while(!work.next().done){}}
 expect(shared.calls.filter(x=>x==='content-painted')).toHaveLength(3);expect(shared.calls.filter(x=>x.startsWith('canonical-base:'))).toEqual(['canonical-base:0','canonical-base:1','canonical-base:2']);expect(owner.snapshot().owners).toHaveLength(0);owner.dispose()
})
it('cross-wash rejection precedes original pointer mutation and keeps existing overlay',()=>{
 const {e,owner,scratch,status}=fixture();e._onStart({});e._finishRibbonStroke(scratch);e._strokeLayerId=null;const before=e._asyncLocalPreviewTiles().get('layer')[0].buffer;e._activeId='different';e._onStart({});expect(scratch.gesture).toBe(1);expect(status).toHaveBeenLastCalledWith(expect.stringContaining('сменой'));expect(e._asyncLocalPreviewTiles().get('layer')[0].buffer).toBe(before);owner.dispose()
})
it('dispose cancels pending canonical work and fences active lease before restoring the ordinary renderer',()=>{
 const {e,owner,scratch,requests}=fixture();e._onStart({});e._finishRibbonStroke(scratch);const work=requests[0].execute();work.next();expect(owner.snapshot().active).not.toBeNull();owner.dispose();expect(e.gl.finish).toHaveBeenCalled();expect(owner.snapshot().active).toBeNull();expect(owner.snapshot().bytes).toBe(0);expect(e._wcAsyncFinish).toBeUndefined();owner.dispose()
})

it('diagnostic last-owner transfer copies actual visible buffer and holds explicit reject policy without touching canonical capture',()=>{shared.calls=[];const{e,owner,scratch,status}=fixture({diagnosticLastOwnerMorph:true});expect(owner.prewarmedRevealBytes).toBe(16*1024*1024);e._onStart({});e._finishRibbonStroke(scratch);e._finishRibbonStroke(scratch,true,true,false,{gesture:1});expect(shared.calls.filter(x=>x==='copy-visible-to-reveal')).toHaveLength(1);expect(e._asyncLocalPreviewTiles().get('layer')).toBeUndefined();e._onStart({});expect(scratch.gesture).toBe(1);expect(status).toHaveBeenLastCalledWith(expect.stringContaining('не пользовательский'));expect(owner.trace.some((x:any)=>x.kind==='diagnostic-morph-transfer')).toBe(true);owner.dispose()})
it('older finish cannot transfer or hide a newer owner presentation',()=>{shared.calls=[];const{e,owner,scratch}=fixture({diagnosticLastOwnerMorph:true});e._onStart({});e._finishRibbonStroke(scratch);e._onStart({});const visible=e._asyncLocalPreviewTiles().get('layer')[0].buffer;scratch.gesture=1;e._finishRibbonStroke(scratch,true,true,false,{gesture:1});expect(shared.calls.filter(x=>x==='copy-visible-to-reveal')).toHaveLength(0);expect(e._asyncLocalPreviewTiles().get('layer')[0].buffer).toBe(visible);owner.dispose()})

it('material rebase keeps three admissions open, sequential late bases and newer overlay ownership',()=>{
 shared.calls=[];const{e,owner,scratch,requests,status}=fixture({diagnosticMaterialRebase:true});expect(owner.prewarmedRevealBytes).toBe(32*1024*1024);expect(owner.prewarmedVisualScratchBytes).toBe(8*1024*1024);
 for(let n=0;n<3;n++){e._onStart({});e._finishRibbonStroke(scratch);e._strokeLayerId=null}
 const latest=e._asyncLocalPreviewTiles().get('layer')[0].buffer;for(let n=0;n<2;n++){const work=requests.shift().execute();while(!work.next().done){}}
 expect(shared.calls.filter(x=>x.startsWith('material-rebase:'))).toEqual(['material-rebase:2:1','material-rebase:3:1']);expect(e._asyncLocalPreviewTiles().get('layer')[0].buffer).toBe(latest);expect(owner.trace.filter((x:any)=>x.kind==='material-rebase').map((x:any)=>x.epoch)).toEqual([1,1]);
 while(requests.length){const work=requests.shift().execute();while(!work.next().done){}}
 expect(shared.calls.filter(x=>x.startsWith('material-rebase:'))).toEqual(['material-rebase:2:1','material-rebase:3:1','material-rebase:3:2']);expect(owner.snapshot().owners).toHaveLength(0);expect(status).not.toHaveBeenCalledWith(expect.stringContaining('не пользовательский'));owner.dispose();
})
it('new DOWN during canonical reveal remains admitted and brackets immediate visual source',()=>{
 shared.calls=[];const{e,owner,scratch,requests,status}=fixture({diagnosticMaterialRebase:true});e._onStart({});e._finishRibbonStroke(scratch);e._strokeLayerId=null;while(requests.length){const work=requests.shift().execute();while(!work.next().done){}}
 expect(e._washReveals.size).toBeGreaterThan(0);e._onStart({});expect(scratch.gesture).toBe(2);expect(shared.calls.filter(x=>x==='visual-before')).toHaveLength(2);expect(shared.calls.filter(x=>x==='visual-after')).toHaveLength(2);expect(status).toHaveBeenLastCalledWith('');expect(owner.trace.some((x:any)=>x.kind==='owned-reveal-inherit')).toBe(true);owner.dispose();
})

it('qaReuse actual frozen installer releases main bundle only after existing sync then admits fourth',()=>{const{e,owner,scratch,requests}=fixture({qaReuseOwners:true});for(let n=0;n<3;n++){e._onStart({});e._finishRibbonStroke(scratch);e._strokeLayerId=null}e._onStart({});expect(scratch.gesture).toBe(3);while(requests.length){const work=requests.shift().execute();while(!work.next().done){}}e._onStart({});expect(scratch.gesture).toBe(3);e._syncContinuationGpu();e._onStart({});expect(scratch.gesture).toBe(4);e._strokeLayerId=null;owner.dispose()});

it('actual current ROOT listener closes pool and cancels lost future jobs without issuing idle; stale DOWN ignored',()=>{const {e,owner}=fixture({qaReuseOwners:true});e._onStart();e.gl.isContextLost=()=>true;const syncCalls=e.gl.finish.mock.calls.length;e.__listeners.get('webglcontextlost')();expect(shared.calls).toContain('close-lost');expect(shared.calls).toContain('destroy-lost');expect(e.gl.finish.mock.calls.length).toBe(syncCalls);const count=shared.calls.filter((x:string)=>x==='visible-source').length;e._onStart();expect(shared.calls.filter((x:string)=>x==='visible-source')).toHaveLength(count);owner.dispose()});
it('reuse dispose of active canonical releases after existing finish without post-certificate copy',()=>{const{e,rawGl,owner,scratch,requests}=fixture({qaReuseOwners:true});e._onStart();e._finishRibbonStroke(scratch);const work=requests[0].execute();work.next();expect(owner.snapshot().active).not.toBeNull();e._syncContinuationGpu();const copies=rawGl.copyTexSubImage2D.mock.calls.length+rawGl.copyTexImage2D.mock.calls.length;owner.dispose();expect(owner.snapshot().active).toBeNull();expect(owner.snapshot().bytes).toBe(0);expect(rawGl.copyTexSubImage2D.mock.calls.length+rawGl.copyTexImage2D.mock.calls.length).toBe(copies);owner.dispose()});

it('actual early-preview active disposal discards preview without beforeRebase copy after known idle',async()=>{const{e,rawGl,owner,scratch,requests}=fixture({qaReuseOwners:true,diagnosticEarlyPreview:true,diagnosticMaterialRebase:true});await owner.previewReady;e._onStart();e._finishRibbonStroke(scratch);const work=requests[0].execute();work.next();expect(owner.snapshot().active).not.toBeNull();const oldCopy=rawGl.copyTexSubImage2D.mock.calls.length;owner.dispose();expect(rawGl.copyTexSubImage2D.mock.calls.length).toBe(oldCopy);expect(shared.calls).toContain('preview-retire');expect(owner.snapshot().active).toBeNull()});
