import{it,expect,vi}from'vitest'
const state=vi.hoisted(()=>({next:0,events:[]as string[]}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/apps/web/src/engine/src/buffers/AccumulationBuffer.ts',()=>({AccumulationBuffer:class{width=1024;height=1024;texture={id:++state.next};clear(){}copyTo(){}destroy(){state.events.push('destroy')}}}))
vi.mock('/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/PreparedGlSourceDraw.ts',()=>({createPreparedGlSourcePort:(input:any)=>({bindCurrentCanonical:input.bindCurrentCanonical,clear(){},copy(){},draw(){},basePlusFilm(){}})}))
import{PrewarmedGlOwnerPool}from'/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/PrewarmedGlOwnerPool'
import{OwnedGlPreparedSource}from'/home/suselman/projects/pencil-agents/728-solvent-init/docs/qa/harness/728-gl-queue-batch/OwnedGlPreparedSource'
import{OwnedQaBundleRetirement}from'./OwnedQaBundleRetirement.mjs'
it('actual39mainfields+actualpreparedchunk retained throughland, futureCPU and staleidle; then fourthreuse withoutDOWNfinish',()=>{
 const pool=new PrewarmedGlOwnerPool({}as WebGLRenderingContext,3,156*1024*1024),retire=new OwnedQaBundleRetirement({generation:1});let future=true,previewReleased=0;
 const owners=Array.from({length:3},(_,i)=>{const empty=Object.fromEntries(['presentation','original','coverage','coverageFilm','pigmentLoad','pigmentBase','pigmentFilm','colourLoad','colourBase','colourFilm','solventLoad','solventBase','solventFilm'].map(k=>[k,null]));const lease=pool.take(empty as any)!;const source=new OwnedGlPreparedSource({lease,context:{}as any,ribbon:{drawRibbonCompositeRect(){}}as any,watercolor:{}as any,retainForRebase:true,ownerToken:{layerId:'L',gesture:i+1}});source.paint({commands:[],rect:null,film:false,waterOnly:false,composite:{preset:{hardness:1},profile:{normalizeDeposit:false},bounds:{minX:1,minY:1,maxX:2,maxY:2}}as any});const owner={token:{sequence:i},source,lease};expect(retire.admit(owner,{detachPresentation(){},releasePreview(){previewReleased++},hasFutureCpuJobs:()=>i===0&&future})).toBe(true);retire.noteConsumer(owner);return owner});
 const originalPayload=owners[0].source.retainedPayloadBytes;expect(originalPayload).toBeGreaterThan(0);expect(pool.free).toBe(0);const before=retire.captureBeforeExistingSync();expect(retire.requestLandOrCancel(owners[0])).toBe(false);retire.afterExistingSyncReturns(before,'gl.finish');expect(pool.free).toBe(0);expect(owners[0].source.retainedPayloadBytes).toBe(originalPayload);
 future=false;retire.refreshAfterJobs();retire.afterExistingSyncReturns(before,'gl.finish');expect(pool.free).toBe(0);expect(previewReleased).toBe(0);
 retire.afterExistingSyncReturns(retire.captureBeforeExistingSync(),'gl.finish');expect(pool.free).toBe(1);expect(owners[0].source.retainedPayloadBytes).toBe(0);expect(previewReleased).toBe(1);const fourth=pool.take(Object.fromEntries(Object.keys(owners[0].lease.fields).map(k=>[k,null]))as any)!;expect(fourth.fields).toBe(owners[0].lease.fields);fourth.release();for(const o of owners.slice(1))retire.requestLandOrCancel(o);retire.afterExistingSyncReturns(retire.captureBeforeExistingSync(),'gl.finish');expect(previewReleased).toBe(3);pool.disposeAfterFence();expect(state.events).toHaveLength(39);
})
