import{it,expect}from'vitest'
import{OperationLog}from'./OperationLog'
import{makeStroke,dab}from'../../testing/engineTestUtils'
import type{Operation}from'@grafetto/shared'
it('exact transaction restores backfilled mixed gesture states and counts after failed redo',()=>{const log=new OperationLog(),a={...makeStroke('A','L',[dab(1,1)]),id:'a',strokeId:'G'},b={...a,id:'b'};log.append(b);log.applyUndo('b','A');log.prependHistorical([{op:a,state:'done',serverSeq:1}]);const states=log.entries.map(e=>[e.op.id,e.state]),count=log.pixelOpDoneCount('L'),cp=log.captureHistoryStates('b'),control:Operation={id:'redo',type:'operation_redo',targetOpId:'b',userId:'A',timestamp:1};log.append(control,{pending:true});log.applyRedo('b','A');log.rollbackUnemittedHistory(control,cp);expect(log.entries.filter(e=>e.op.type==='stroke').map(e=>[e.op.id,e.state])).toEqual(states);expect(log.pixelOpDoneCount('L')).toBe(count);expect(log.entries.find(e=>e.op.id==='redo')?.state).toBe('gone');expect(()=>log.rollbackUnemittedHistory(control,cp)).toThrow('foreign')})
it('foreign and intervening mutations cannot reuse checkpoint',()=>{const log=new OperationLog(),other=new OperationLog(),source={...makeStroke('A','L',[dab(1,1)]),id:'source'};log.append(source);const cp=log.captureHistoryStates('source'),control:Operation={id:'undo',type:'operation_undo',targetOpId:'source',userId:'A',timestamp:1};expect(()=>other.rollbackUnemittedHistory(control,cp)).toThrow('foreign');log.append({...source,id:'peer',userId:'B'});expect(()=>log.rollbackUnemittedHistory(control,cp)).toThrow('Intervening')})
it('rejected uncertain backfill preserves exact transaction witness; accepted page invalidates old owner witness',()=>{
 const log=new OperationLog(),b={...makeStroke('A','L',[dab(2,2)]),id:'b',strokeId:'G',seq:2},a={...b,id:'a',seq:1};log.append(b,{serverSeq:2});log.applyUndo('b','A');const cp=log.captureHistoryStates('b'),revision=log.revision,entry=log.entries[0],control:Operation={id:'redo',type:'operation_redo',targetOpId:'b',userId:'A',timestamp:1};expect(log.prependHistoricalReconciled([{op:a,state:'done',serverSeq:1}])).toHaveLength(1);expect(log.revision).toBe(revision);expect(log.entries[0]).toBe(entry);log.append(control,{pending:true});log.applyRedo('b','A');log.rollbackUnemittedHistory(control,cp);expect(log.entries.find(e=>e.op.id==='b')?.state).toBe('undone');expect(log.pixelOpDoneCount('L')).toBe(0);
 const fresh=log.captureHistoryStates('b'),undo:Operation={id:'known-undo',type:'operation_undo',targetOpId:'b',userId:'A',timestamp:3,seq:3};expect(log.prependHistoricalReconciled([{op:a,state:'done',serverSeq:1},{op:undo,state:'done',serverSeq:3}])).toEqual([]);expect(()=>log.rollbackUnemittedHistory({...control,id:'unemitted'},fresh)).toThrow();expect(log.entries.filter(e=>e.op.type==='stroke').map(e=>e.state)).toEqual(['undone','undone']);expect(log.pixelOpDoneCount('L')).toBe(0)
})
