/// <reference types="@webgpu/types" />
import {DISPLAY_VERT} from '../../../../apps/web/src/engine/src/raster/shaders'
import {decodePreBrush68Checkpoint} from './preBrush68Codec'
import {BRUSH68_ROI as R,BRUSH68_FLOW_RECT} from './preBrush68Checkpoint'
import {runPreBrush68NativeGate} from './preBrush68NativeGate'
import {brushFractionGlShader,brushFractionWgslShader,brushFractionRows} from './brushFractionProbe'
/** 16 directed faces at TWO actual mismatch cells. Output RGBA32F only,
 * not material replacement. GL full viewport is translated into1x1 FBO to
 * retain original varying UV at the actual1536 pixel, not CPU approximations. */
export async function runBrushFractionOracle(packet:unknown){
 const input=await decodePreBrush68Checkpoint(packet),rows=brushFractionRows(),canvas=document.createElement('canvas');canvas.width=canvas.height=1
 const gl=canvas.getContext('webgl',{premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)throw Error('Fraction GL unavailable')
 const expected=new Float32Array(64),textures:WebGLTexture[]=[],shaders:WebGLShader[]=[];let program:WebGLProgram|null=null,fb:WebGLFramebuffer|null=null,buffer:WebGLBuffer|null=null
 try{
  if(!gl.getExtension('OES_texture_float')||!gl.getExtension('WEBGL_color_buffer_float'))throw Error('Actual RGBA32F target unsupported explicitly')
  program=gl.createProgram()!;for(const[type,code]of [[gl.VERTEX_SHADER,DISPLAY_VERT],[gl.FRAGMENT_SHADER,brushFractionGlShader()]]as const){const s=gl.createShader(type)!;shaders.push(s);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)??'Fraction GL compile');gl.attachShader(program,s)}gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)??'Fraction GL link');gl.useProgram(program)
  const texture=(width:number,height:number,linear=false,type:number=gl.UNSIGNED_BYTE)=>{const t=gl.createTexture()!;textures.push(t);gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,width,height,0,gl.RGBA,type,null);for(const k of[gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,k,linear?gl.LINEAR:gl.NEAREST);for(const k of[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,k,gl.CLAMP_TO_EDGE);return t}
  const fields=input.rows.slice(0,3).map(r=>{const t=texture(1536,1536),b=new Uint8Array(r.bytes.length);for(let y=0;y<R.height;y++)b.set(r.bytes.subarray(y*R.width*4,(y+1)*R.width*4),(R.height-1-y)*R.width*4);gl.texSubImage2D(gl.TEXTURE_2D,0,R.x,1536-R.y-R.height,R.width,R.height,gl.RGBA,gl.UNSIGNED_BYTE,b);return t}),flow=texture(31,26,true);gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,31,26,gl.RGBA,gl.UNSIGNED_BYTE,input.flow);const target=texture(1,1,false,gl.FLOAT);fb=gl.createFramebuffer()!;gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,target,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Fraction actual float framebuffer unsupported')
  buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'a_position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);gl.disable(gl.BLEND);gl.disable(gl.SCISSOR_TEST);[fields[0],flow,fields[2],fields[0],fields[1]].forEach((t,i)=>{gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,t);gl.uniform1i(gl.getUniformLocation(program!,['u_paint','u_flow','u_water','u_pigment','u_color'][i]),i)});gl.uniform2f(gl.getUniformLocation(program,'u_step'),1/1536,1/1536);gl.uniform2f(gl.getUniformLocation(program,'u_texel'),1/1536,1/1536);gl.uniform4fv(gl.getUniformLocation(program,'u_flowRect'),BRUSH68_FLOW_RECT);gl.uniform1f(gl.getUniformLocation(program,'u_contactGain'),.6437950134277344)
  rows.forEach((row,i)=>{gl.viewport(-row.fieldX,-(1535-row.fieldY),1536,1536);gl.uniform1i(gl.getUniformLocation(program!,'u_face'),row.axis);gl.uniform1f(gl.getUniformLocation(program!,'u_take'),+row.take);gl.drawArrays(gl.TRIANGLES,0,6);gl.readPixels(0,0,1,1,gl.RGBA,gl.FLOAT,expected.subarray(i*4,i*4+4))});if(gl.getError()||gl.isContextLost()||expected.some(x=>!Number.isFinite(x)))throw Error('Fraction GL invalid float readback')
 }finally{textures.forEach(t=>gl.deleteTexture(t));shaders.forEach(s=>gl.deleteShader(s));gl.deleteProgram(program);gl.deleteBuffer(buffer);gl.deleteFramebuffer(fb);gl.getExtension('WEBGL_lose_context')?.loseContext()}
 const adapter=await navigator.gpu?.requestAdapter();if(!adapter)throw Error('Fraction WebGPU unsupported explicitly');const device=await adapter.requestDevice(),nativeTextures:GPUTexture[]=[],buffers:GPUBuffer[]=[],errors:string[]=[];let lost=false
 device.addEventListener('uncapturederror',e=>errors.push(e.error.message));void device.lost.then(x=>{if(x.reason!=='destroyed')lost=true})
 try{
  device.pushErrorScope('validation');const field=(width:number,height:number,bytes:Uint8Array,roi=false)=>{const t=device.createTexture({size:[width,height],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});nativeTextures.push(t);device.queue.writeTexture({texture:t,origin:roi?[R.x,R.y]:undefined},bytes,{bytesPerRow:roi?R.width*4:width*4,rowsPerImage:roi?R.height:height},roi?[R.width,R.height]:[width,height]);return t.createView()};const p=field(1536,1536,input.rows[0].bytes,true),c=field(1536,1536,input.rows[1].bytes,true),water=field(1536,1536,input.rows[2].bytes,true),flipped=new Uint8Array(input.flow.length);for(let y=0;y<26;y++)flipped.set(input.flow.subarray((25-y)*124,(26-y)*124),y*124);const flow=field(31,26,flipped)
  const uniform=device.createBuffer({size:80,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}),out=device.createBuffer({size:256,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC}),read=device.createBuffer({size:256,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});buffers.push(uniform,out,read);const values=new Float32Array(20);values.set([1/1536,1/1536,1/1536,1/1536,...BRUSH68_FLOW_RECT,.6437950134277344,0,0,0]);device.queue.writeBuffer(uniform,0,values);const module=device.createShaderModule({code:brushFractionWgslShader()}),pipeline=device.createComputePipeline({layout:'auto',compute:{module,entryPoint:'probe'}}),sampler=device.createSampler({minFilter:'linear',magFilter:'linear',addressModeU:'clamp-to-edge',addressModeV:'clamp-to-edge'}),group=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:uniform}},...[p,c,flow,water].map((v,i)=>({binding:i+1,resource:v})),{binding:5,resource:sampler},{binding:6,resource:{buffer:out}}]}),encoder=device.createCommandEncoder(),pass=encoder.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,group);pass.dispatchWorkgroups(1);pass.end();encoder.copyBufferToBuffer(out,0,read,0,256);device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const actual=new Float32Array(read.getMappedRange()).slice();read.unmap();const glBits=new Uint32Array(expected.buffer),nativeBits=new Uint32Array(actual.buffer),validation=(await device.popErrorScope())?.message??null
  return{code:'__SOURCE_CODE__',producerCode:(packet as any).code,flowSha256:(packet as any).flow.sha256,rows:rows.map((r,i)=>({...r,gl:Array.from(expected.subarray(i*4,i*4+4)),native:Array.from(actual.subarray(i*4,i*4+4)),glBits:Array.from(glBits.subarray(i*4,i*4+4)),nativeBits:Array.from(nativeBits.subarray(i*4,i*4+4))})),columns:['raw','fraction','P.rByte*fraction','floor(P.rByte*fraction)'],glOwnerRetired:true,errors,lost,validation,scope:'TWO actual brush68 mismatch cells ×8 directed donor faces. Same unchanged helper bodies; different float output pipeline can change compiler optimisation. Compare transfers to original material pipeline before calling this a cause. No physical/Q8 output replacement, epsilon, Room, whole solver or performance claim.'}
 }finally{await device.queue.onSubmittedWorkDone().catch(()=>{});buffers.forEach(b=>b.destroy());nativeTextures.forEach(t=>t.destroy());device.destroy()}
}

/** Corroborate diagnostic floats against the unchanged material shader.
 * All THREE owners retire sequentially; no ordinary source reprepare. */
export async function runBrushFractionGate(packet:unknown){
 const floats=await runBrushFractionOracle(packet)
 if(floats.validation||floats.errors.length||floats.lost)throw Error('Fraction float pipeline invalid')
 const material=await runPreBrush68NativeGate(packet),input=await decodePreBrush68Checkpoint(packet)
 if(material.validation||material.errors.length||material.lost)throw Error('Fraction original material pipeline invalid')
 const reconstruction=[0,1].map(i=>{const rows=floats.rows.slice(i*8,i*8+8),x=rows[0].fieldX,y=rows[0].fieldY,k=((y-R.y)*R.width+x-R.x)*4,old=input.rows[0].bytes[k],gl=old+rows.slice(4).reduce((a,r)=>a+r.gl[3],0)-rows.slice(0,4).reduce((a,r)=>a+r.gl[3],0),native=old+rows.slice(4).reduce((a,r)=>a+r.native[3],0)-rows.slice(0,4).reduce((a,r)=>a+r.native[3],0),glOriginal=input.rows[3].bytes[k],nativeOriginal=material.comparisons[0].witnesses[i].actual[0];return{x,y,old,glFloatReconstruction:gl,nativeFloatReconstruction:native,glOriginal,nativeOriginal,glAgrees:gl===glOriginal,nativeAgrees:native===nativeOriginal}})
 return{code:'__SOURCE_CODE__',floats,material,reconstruction,floatMaterialAgreement:reconstruction.every(r=>r.glAgrees&&r.nativeAgrees),errors:[],lost:false,validation:null,scope:'TWO mismatch cells only. Float-helper diagnosis is causal candidate ONLY if both reconstructions match original Q8 material pipelines. No epsilon, changed fraction/floor, portfix, whole solver or Room claim.'}
}
