/// <reference types="node" />
import fs from 'node:fs'
import {execFileSync} from 'node:child_process'
import {createHash} from 'node:crypto'
import {traceFixture,TraceBuffer} from '../../../../apps/web/src/engine/src/raster/CanonicalWatercolorSettlePlan.fixture'
import {CanonicalWatercolorSettlePlan} from '../../../../apps/web/src/engine/src/raster/CanonicalWatercolorSettlePlan'
const checkpointPath=process.argv[2],outputPath=process.argv[3];if(!checkpointPath||!outputPath)throw Error('Explicit durable checkpoint and trace output required');const packet=JSON.parse(fs.readFileSync(checkpointPath,'utf8'));const plannerPath='apps/web/src/engine/src/raster/CanonicalWatercolorSettlePlan.ts',plannerBytes=fs.readFileSync(plannerPath),frozenPlanner=execFileSync('git',['show',packet.code+':'+plannerPath]);if(!plannerBytes.equals(frozenPlanner))throw Error('Shared CPU planner differs from captured producer');const plannerSha256=createHash('sha256').update(plannerBytes).digest('hex');const f=traceFixture(false,false,true,false,false);let id=1000
const mk=(w:number,h:number)=>new TraceBuffer(++id,w,h,f.record),aliases=new Map(),entry:any={};for(const role of packet.payload.fields){if(role.presence==='field'){if(!aliases.has(role.alias))aliases.set(role.alias,mk(role.width,role.height));entry[role.role]=aliases.get(role.alias)}else if(role.presence==='null')entry[role.role]=null}
const tile=entry.target;delete entry.target;entry.filmGesture=packet.payload.filmGesture;entry.solventGesture=packet.payload.solventGesture;entry.coverageFilmGesture=packet.payload.coverageFilmGesture
const metadata=JSON.parse(packet.payload.metadataJson);Object.assign(f.scratch,metadata,{paints:new Set(metadata.paints),materialGesture:packet.payload.materialGesture,pigmentInputsKnownZero:packet.payload.pigmentInputsKnownZero,peek:()=>entry,*tileEntries(){yield[tile,entry]}})
f.context.fieldFor=()=>Object.fromEntries([['w',1536],['h',1536],...['a','b','c','ca','cb','cc','coverage','mask','pressure','band'].map(role=>[role,mk(1536,1536)])]) as any
f.context.paperWorldSize=()=>packet.config.paperWorld;f.context.ab=()=>packet.config.ab;f.context.gradientFibres=()=>packet.config.gradientFibres;f.context.shouldPreview=()=>false
const plan=new CanonicalWatercolorSettlePlan(f.context);Object.assign(plan,packet.config.plannerFlags);const args=JSON.parse(packet.payload.scalarsJson),job=(plan.prepare as any)(f.scratch,[{buffer:tile,originX:0,originY:0,contentRect:null}],...args,undefined,false,f.scratch)
if(!job)throw Error('Actual packet job missing');const ops=[];for(let i=0;i<Math.min(job.ops.length,8);i++){const offset=f.events.length;job.ops[i]();ops.push({index:i,events:f.events.slice(offset)})}job.dispose();plan.destroyTextures();fs.writeFileSync(outputPath,JSON.stringify({scope:'CPU shared planner chronology from actual same-device source packet; no pixel proof',sourceCode:packet.code,packetSha256:createHash('sha256').update(fs.readFileSync(checkpointPath)).digest('hex'),plannerSha256,ops},null,2));console.log(JSON.stringify(ops.map(op=>({index:op.index,events:op.events.map((e:any)=>[e[0],e[0]==='fieldOp'?e[4]:null])}))))
