/// <reference types="@webgpu/types" />
import {DISPLAY_VERT,WC_FIELD_OP_FRAG,WC_FIELD_OP_HIGH_FRAG} from '../../../../apps/web/src/engine/src/raster/shaders'
import {CanonicalFieldOps} from '../../../../apps/web/src/engine/src/webgpuCanonical/passes/fieldOps'
import type {CanonicalGpuField} from '../../../../apps/web/src/engine/src/webgpuCanonical/types'
import {FIRST_BAND_INPUTS,FIRST_BAND_RECIPE,firstBandDiagnosticWorld,validateFirstBandInputs,type FirstBandSnapshot} from './firstBandInputContract'
import {boundedByteDifferences} from './inwardDiagnostic'
import {rimCornerQaRecipe,rimCornerQaShaders,uploadGlRimCorners,encodeRimCornerQa,rimBandGImage} from './rimCornerTextureQa'
export function seededRimPatternDifferences(actual:Uint8Array,baseline:Uint8Array,width:number){return boundedByteDifferences(actual,baseline,width,32,true)}
const W=1536,BYTES=W*W*4
const sha=async(a:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a.slice().buffer)),x=>x.toString(16).padStart(2,'0')).join('')
const flip=(a:Uint8Array)=>{const b=new Uint8Array(BYTES);for(let y=0;y<W;y++)b.set(a.subarray(y*W*4,(y+1)*W*4),(W-y-1)*W*4);return b}
export interface FirstBandCommonInput {pressure:Uint8Array;inward:Uint8Array;coverage:Uint8Array;packetSha256:string;producerCode:string;mode:11|6;diagnosticRimPatchOff?:true;diagnosticSeededRimCorners?:true}
/** Both APIs consume SAME GL Q8 fields; native does not repeat pressure/front/source preparation. */
export async function runFirstBandCommonOracle(input:FirstBandCommonInput){
 if(!/^[a-f0-9]{40}$/.test(input.producerCode)||input.packetSha256!=='1cf7698e3d2fa6a713a00dad8d2e7f0d05dbb7f74139c91096e366d74560e76f'||![11,6].includes(input.mode))throw Error('Actual first band source passport')
 if(input.diagnosticSeededRimCorners&&(input.mode!==6||input.diagnosticRimPatchOff))throw Error('Seeded corners require original mode6 world1')
 const cornerTable=input.diagnosticSeededRimCorners?rimCornerQaRecipe():null
 const actualWorld=firstBandDiagnosticWorld(input.mode,input.diagnosticRimPatchOff)
 const manifest:FirstBandSnapshot[]=[]
 for(const role of ['pressure','inward','coverage'] as const){if(input[role].length!==BYTES)throw Error('Common role byte size');manifest.push({role,sha256:await sha(input[role]),filter:FIRST_BAND_INPUTS[role].filter,width:W,height:W,bytes:BYTES,rowConvention:'world-top',packetSha256:input.packetSha256,sourceApi:'GL'})}
 validateFirstBandInputs(manifest,input.packetSha256)
 const c=document.createElement('canvas');c.width=c.height=W;const gl=c.getContext('webgl',{premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)throw Error('First band GL unavailable')
 const textures:WebGLTexture[]=[],programs:WebGLProgram[]=[],shaders:WebGLShader[]=[];let fb:WebGLFramebuffer|null=null,buffer:WebGLBuffer|null=null,expected:Uint8Array,extended:Uint8Array,glError=0,baseline:Uint8Array|undefined
 try{
  const tex=(bytes:Uint8Array|null,linear=false)=>{const t=gl.createTexture()!;textures.push(t);gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,W,W,0,gl.RGBA,gl.UNSIGNED_BYTE,bytes?flip(bytes):null);for(const k of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,k,linear?gl.LINEAR:gl.NEAREST);for(const k of [gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,k,gl.CLAMP_TO_EDGE);return t}
  const cornerTexture=cornerTable?uploadGlRimCorners(gl,cornerTable):null;if(cornerTexture)textures.push(cornerTexture)
  const pressure=tex(input.pressure,true),inward=tex(input.inward,true),coverage=tex(input.coverage),extension=tex(null),band=tex(null)
  fb=gl.createFramebuffer()!;gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.viewport(0,0,W,W);gl.disable(gl.BLEND);gl.disable(gl.SCISSOR_TEST);buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW)
  const program=(fragment:string)=>{const p=gl.createProgram()!;programs.push(p);for(const[type,source] of [[gl.VERTEX_SHADER,DISPLAY_VERT],[gl.FRAGMENT_SHADER,fragment]] as const){const s=gl.createShader(type)!;shaders.push(s);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)??'Band shader');gl.attachShader(p,s)}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)??'Band program');return p}
  const draw=(mode:11|6,a:WebGLTexture,b:WebGLTexture,target:WebGLTexture,p:WebGLProgram)=>{gl.useProgram(p);const pos=gl.getAttribLocation(p,'a_position');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const r=mode===11?FIRST_BAND_RECIPE.mode11:FIRST_BAND_RECIPE.mode6;for(const[i,t]of[[0,a],[1,b],[2,inward],[3,pressure],[4,coverage],[5,coverage],[6,coverage]] as const){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,t);gl.uniform1i(gl.getUniformLocation(p,['u_a','u_b','u_c','u_d','u_e','u_path','u_wcFibreNoiseTex'][i]),i)}if(cornerTexture){gl.activeTexture(gl.TEXTURE7);gl.bindTexture(gl.TEXTURE_2D,cornerTexture);gl.uniform1i(gl.getUniformLocation(p,'u_qaRimCorners'),7)}gl.uniform1f(gl.getUniformLocation(p,'u_mode'),mode);gl.uniform1f(gl.getUniformLocation(p,'u_k'),r.k);for(const[n,v]of Object.entries({u_band:r.band,u_size:r.size,u_dir:[1/W,1/W],u_origin:[1,1],u_tau:[0,0,0],u_world:actualWorld})){if(v.length===3)gl.uniform3fv(gl.getUniformLocation(p,n),v);else gl.uniform2fv(gl.getUniformLocation(p,n),v)}gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,target,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Band GL framebuffer');gl.drawArrays(gl.TRIANGLES,0,6)}
  draw(11,coverage,coverage,extension,program(WC_FIELD_OP_HIGH_FRAG));const raw=new Uint8Array(BYTES);gl.readPixels(0,0,W,W,gl.RGBA,gl.UNSIGNED_BYTE,raw);extended=flip(raw)
  if(input.mode===6){draw(6,pressure,extension,band,program(WC_FIELD_OP_FRAG));gl.readPixels(0,0,W,W,gl.RGBA,gl.UNSIGNED_BYTE,raw);if(cornerTable){baseline=flip(raw);draw(6,pressure,extension,band,program(rimCornerQaShaders(cornerTable).gl));gl.readPixels(0,0,W,W,gl.RGBA,gl.UNSIGNED_BYTE,raw)}}expected=flip(raw);glError=gl.getError();if(glError||gl.isContextLost())throw Error('First band GL error/loss')
 }finally{textures.forEach(t=>gl.deleteTexture(t));programs.forEach(p=>gl.deleteProgram(p));shaders.forEach(s=>gl.deleteShader(s));gl.deleteBuffer(buffer);gl.deleteFramebuffer(fb);gl.getExtension('WEBGL_lose_context')?.loseContext()}
 const adapter=await navigator.gpu?.requestAdapter();if(!adapter)throw Error('First band native unavailable');const device=await adapter.requestDevice(),fields:CanonicalGpuField[]=[],uniforms:GPUBuffer[]=[],errors:string[]=[];let read:GPUBuffer|undefined,cornerResources:ReturnType<typeof encodeRimCornerQa>|undefined,lost=false;device.addEventListener('uncapturederror',e=>errors.push(e.error.message));void device.lost.then(i=>{if(i.reason!=='destroyed')lost=true})
 try{
  const field=(bytes?:Uint8Array,filter:'linear'|'nearest'='nearest')=>{const texture=device.createTexture({size:[W,W],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST});const f:CanonicalGpuField={texture,view:texture.createView(),width:W,height:W,format:'rgba8unorm',filter,label:'common GL first band'};fields.push(f);if(bytes)device.queue.writeTexture({texture},bytes,{bytesPerRow:W*4},{width:W,height:W});return f}
  const pressure=field(input.pressure,'linear'),inward=field(input.inward,'linear'),coverage=field(input.coverage),extension=field(input.mode===6?extended!:undefined),band=field(),encoder=device.createCommandEncoder(),ctx={device,encoder,nearest:device.createSampler(),linear:device.createSampler({minFilter:'linear',magFilter:'linear'})},ops=new CanonicalFieldOps(device);device.pushErrorScope('validation')
  const base={coverage,paper:{field:coverage,origin:[0,0] as [number,number],texSize:[1024,1024] as [number,number],scale:1},world:{x:0,y:0,width:W,height:W}}
  if(input.mode===11)uniforms.push(ops.run(ctx,{...base,a:coverage,b:coverage,out:extension},11,1,{d:pressure,band:FIRST_BAND_RECIPE.mode11.band,size:FIRST_BAND_RECIPE.mode11.size}))
  if(input.mode===6&&cornerTable)cornerResources=encodeRimCornerQa(device,encoder,{pressure,inward,coverage,extension,band},cornerTable)
  if(input.mode===6&&!cornerTable)uniforms.push(ops.run(ctx,{...base,a:pressure,b:extension,out:band},6,1,{c:inward,d:pressure,band:FIRST_BAND_RECIPE.mode6.band,size:FIRST_BAND_RECIPE.mode6.size,origin:[1,1],dir:[1,1],tau:[0,0,0],world:actualWorld}))
  read=device.createBuffer({size:BYTES,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});encoder.copyTextureToBuffer({texture:(input.mode===6?band:extension).texture},{buffer:read,bytesPerRow:W*4},{width:W,height:W});device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const actual=new Uint8Array(read.getMappedRange()).slice(),validation=(await device.popErrorScope())?.message??null,diff=boundedByteDifferences(actual,expected!,W,32,true)
  const seededRimCorners=cornerTable?{seed:cornerTable.seed,origin:cornerTable.origin,width:cornerTable.width,height:cornerTable.height,bytes:cornerTable.bytes,sha256:await sha(new Uint8Array(cornerTable.values.buffer)),filter:'nearest',rowConvention:cornerTable.rowConvention,visualG:{baseline:rimBandGImage(baseline!),seededGl:rimBandGImage(expected!),seededNative:rimBandGImage(actual)},patternChange:seededRimPatternDifferences(expected!,baseline!,W),limits:'OFF QA DIFFERENT lattice hash/spatial pattern; original frequencies/interpolation/threshold fixed. Not legacy-appearance fidelity fix.'}:null
  return {code:'__SOURCE_CODE__',seededRimCorners,diagnosticRimPatchOff:input.diagnosticRimPatchOff??false,actualWorld,operator:'firstBandCommonInput',mode:input.mode,producerCode:input.producerCode,inputManifest:manifest,recipe:FIRST_BAND_RECIPE,glExtensionSha256:await sha(extended!),nativeExecutedModes:[input.mode],commonExtensionFromGL:input.mode===6,expectedSha256:await sha(expected!),actualSha256:await sha(actual),...diff,exact:diff.channels.every(c=>c.changed===0),glOwnerRetired:true,glError,errors,lost,validation,width:W,height:W,limits:'COMMON GL pressure141/inward11/coverage, native ONLY selectedmode11 ormode6(common GLmode11extension); no inward rerun/native source, carry,brush,maxspread/fullRoom or performance claim'}
 }finally{cornerResources?.texture.destroy();cornerResources?.uniform.destroy();read?.destroy();uniforms.forEach(u=>u.destroy());fields.forEach(f=>f.texture.destroy());device.destroy()}
}
/** Explicit durable exporter, never automatic/never Array<number>. Consumer persists JSON
 * before requesting another GPU owner. Uncompressed role SHA stays authoritative. */
export async function packFirstBandCommonInput(input:FirstBandCommonInput){
 if(!/^[a-f0-9]{40}$/.test(input.producerCode)||input.packetSha256!=='1cf7698e3d2fa6a713a00dad8d2e7f0d05dbb7f74139c91096e366d74560e76f'||![11,6].includes(input.mode))throw Error('Durable band source passport')
 firstBandDiagnosticWorld(input.mode,input.diagnosticRimPatchOff)
 const roles=[]
 for(const role of ['pressure','inward','coverage'] as const){const bytes=input[role];if(bytes.length!==BYTES||await sha(bytes)!==FIRST_BAND_INPUTS[role].sha256)throw Error('Durable first band role differs');const reader=new Blob([bytes.slice().buffer]).stream().pipeThrough(new CompressionStream('gzip')).getReader(),chunks:Uint8Array[]=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>BYTES+8192)throw Error('Durable gzip role bound');chunks.push(value)}}finally{await reader.cancel().catch(()=>{})}const packed=new Uint8Array(size);let offset=0;for(const chunk of chunks){packed.set(chunk,offset);offset+=chunk.length}let binary='';for(let i=0;i<size;i+=16384)binary+=String.fromCharCode(...packed.subarray(i,i+16384));roles.push({role,sha256:FIRST_BAND_INPUTS[role].sha256,filter:FIRST_BAND_INPUTS[role].filter,width:W,height:W,bytes:BYTES,rowConvention:'world-top' as const,packetSha256:input.packetSha256,sourceApi:'GL' as const,gzipBytes:size,gzipSha256:await sha(packed),gzipBase64:btoa(binary)})}
 validateFirstBandInputs(roles,input.packetSha256)
 return {schema:'first-band-common-gl-q8-v1',code:'__SOURCE_CODE__',producerCode:input.producerCode,packetSha256:input.packetSha256,mode:input.mode,diagnosticRimPatchOff:input.diagnosticRimPatchOff??false,roles}
}
