/// <reference types="@webgpu/types" />
import {DISPLAY_VERT,WC_FIELD_OP_CARRY_FRAG}from'../../../../apps/web/src/engine/src/raster/shaders'
import {CanonicalFieldOps}from'../../../../apps/web/src/engine/src/webgpuCanonical/passes/fieldOps'
import type{CanonicalGpuField}from'../../../../apps/web/src/engine/src/webgpuCanonical/types'
import{FIRST_CARRY_INPUTS,FIRST_CARRY_RECIPE,validateFirstCarryInputs,type FirstCarrySnapshot}from'./firstCarryInputContract'
import{boundedByteDifferences}from'./inwardDiagnostic'
export const firstCarryReferenceFragment=WC_FIELD_OP_CARRY_FRAG
const W=1536,BYTES=W*W*4,sha=async(v:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',v.slice().buffer)),x=>x.toString(16).padStart(2,'0')).join(''),flip=(v:Uint8Array)=>{const b=new Uint8Array(BYTES);for(let y=0;y<W;y++)b.set(v.subarray(y*W*4,(y+1)*W*4),(W-y-1)*W*4);return b}
export async function runFirstCarryOracle(input:{mobile:Uint8Array;pressure:Uint8Array;packetSha256:string;producerCode:string;diagnosticHardwareLinearPressure?:true;expectedReferenceSha256?:string}){
 if(input.expectedReferenceSha256!==undefined&&!/^[a-f0-9]{64}$/.test(input.expectedReferenceSha256))throw Error('Explicit first carry reference SHA')
 if(!/^[a-f0-9]{40}$/.test(input.producerCode))throw Error('First carry producer code')
 const manifest:FirstCarrySnapshot[]=[];for(const role of['mobile','pressure']as const){if(input[role].length!==BYTES)throw Error('First carry byte length');manifest.push({role,filter:FIRST_CARRY_INPUTS[role].filter,sha256:await sha(input[role]),width:W,height:W,bytes:BYTES,rowConvention:'world-top',sourceApi:'GL',packetSha256:input.packetSha256})}validateFirstCarryInputs(manifest,input.packetSha256)
 const canvas=document.createElement('canvas');canvas.width=canvas.height=W;const gl=canvas.getContext('webgl',{premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)throw Error('First carry GL unavailable');const textures:WebGLTexture[]=[],shaders:WebGLShader[]=[];let program:WebGLProgram|null=null,buffer:WebGLBuffer|null=null,fb:WebGLFramebuffer|null=null,expected:Uint8Array
 try{
  program=gl.createProgram()!;for(const[type,code]of[[gl.VERTEX_SHADER,DISPLAY_VERT],[gl.FRAGMENT_SHADER,firstCarryReferenceFragment]]as const){const s=gl.createShader(type)!;shaders.push(s);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)??'Carry compile');gl.attachShader(program,s)}gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)??'Carry link');gl.useProgram(program)
  const texture=(bytes:Uint8Array|null,linear=false)=>{const t=gl.createTexture()!;textures.push(t);gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,W,W,0,gl.RGBA,gl.UNSIGNED_BYTE,bytes?flip(bytes):null);for(const k of[gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,k,linear?gl.LINEAR:gl.NEAREST);for(const k of[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,k,gl.CLAMP_TO_EDGE);return t}
  const mobile=texture(input.mobile),pressure=texture(input.pressure,true),out=texture(null);fb=gl.createFramebuffer()!;gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,out,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Carry GL target');gl.viewport(0,0,W,W);gl.disable(gl.BLEND);gl.disable(gl.SCISSOR_TEST);buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'a_position');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0)
  for(let i=0;i<7;i++){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,i===3?pressure:mobile);gl.uniform1i(gl.getUniformLocation(program,['u_a','u_b','u_c','u_d','u_e','u_path','u_wcFibreNoiseTex'][i]),i)}const r=FIRST_CARRY_RECIPE;gl.uniform1f(gl.getUniformLocation(program,'u_mode'),15);gl.uniform1f(gl.getUniformLocation(program,'u_k'),r.k);for(const[n,v]of Object.entries({u_dir:[1/W,1/W],u_band:r.band,u_size:r.size,u_tau:r.tau,u_origin:r.origin,u_world:[0,0,0]})){if(v.length===3)gl.uniform3fv(gl.getUniformLocation(program,n),v);else gl.uniform2fv(gl.getUniformLocation(program,n),v)}gl.drawArrays(gl.TRIANGLES,0,6);const raw=new Uint8Array(BYTES);gl.readPixels(0,0,W,W,gl.RGBA,gl.UNSIGNED_BYTE,raw);expected=flip(raw);if(gl.getError()||gl.isContextLost())throw Error('Carry GL error/lost')
 }finally{textures.forEach(t=>gl.deleteTexture(t));shaders.forEach(s=>gl.deleteShader(s));gl.deleteProgram(program);gl.deleteBuffer(buffer);gl.deleteFramebuffer(fb);gl.getExtension('WEBGL_lose_context')?.loseContext()}
 const referenceSha256=await sha(expected!);if(input.expectedReferenceSha256&&referenceSha256!==input.expectedReferenceSha256)throw Error('First carry GL reference changed; sampler comparison refused before native allocation')
 const adapter=await navigator.gpu?.requestAdapter();if(!adapter)throw Error('Carry native unavailable');const device=await adapter.requestDevice(),fields:CanonicalGpuField[]=[],errors:string[]=[];let uniform:GPUBuffer|undefined,read:GPUBuffer|undefined,lost=false;device.addEventListener('uncapturederror',e=>errors.push(e.error.message));void device.lost.then(i=>{if(i.reason!=='destroyed')lost=true})
 try{
  device.pushErrorScope('validation');const field=(bytes?:Uint8Array,filter:'linear'|'nearest'='nearest')=>{const texture=device.createTexture({size:[W,W],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST}),f:CanonicalGpuField={texture,view:texture.createView(),width:W,height:W,format:'rgba8unorm',filter,label:'common first carry'};fields.push(f);if(bytes)device.queue.writeTexture({texture},bytes,{bytesPerRow:W*4},{width:W,height:W});return f};const mobile=field(input.mobile),pressure=field(input.pressure,'linear'),out=field(),encoder=device.createCommandEncoder(),r=FIRST_CARRY_RECIPE;uniform=new CanonicalFieldOps(device).run({device,encoder,nearest:device.createSampler(),linear:device.createSampler({minFilter:'linear',magFilter:'linear'})},{a:mobile,b:mobile,coverage:mobile,paper:{field:mobile,origin:[0,0],texSize:[1024,1024],scale:1},out,world:{x:0,y:0,width:W,height:W}},15,r.k,{d:pressure,dir:r.dir,band:r.band,size:r.size,tau:r.tau,origin:r.origin,pathPacked:false,additiveZeroFaces:false,diagnosticHardwareLinearInputs:input.diagnosticHardwareLinearPressure});read=device.createBuffer({size:BYTES,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});encoder.copyTextureToBuffer({texture:out.texture},{buffer:read,bytesPerRow:W*4},{width:W,height:W});device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const actual=new Uint8Array(read.getMappedRange()).slice(),validation=(await device.popErrorScope())?.message??null,diff=boundedByteDifferences(actual,expected!,W,32,true)
  return {code:'__SOURCE_CODE__',operator:'firstCarryMode15CommonLiveInputs',sourceFilter:input.diagnosticHardwareLinearPressure?'hardware LINEAR pressure / NEAREST mobile':'manual LINEAR pressure / NEAREST mobile',recipe:r,producerCode:input.producerCode,inputManifest:manifest,...diff,exact:diff.channels.every(c=>c.changed===0),glMovement:boundedByteDifferences(expected!,input.mobile,W,32,true),expectedReferenceSha256:input.expectedReferenceSha256??null,expectedSha256:referenceSha256,actualSha256:await sha(actual),glOwnerRetired:true,glError:0,errors,lost,validation,limits:'ONE original op45 stride1 only. COMMON GL mobile/pressure are ALL live inputs of mode15 with tau.z0/path absent; unused B/C/E/path/noise bindings alias mobile in BOTH APIs. No band/inward carry-through, no paper reads, no later carry/brush/full solver or Room proof.'}
 }finally{read?.destroy();uniform?.destroy();fields.forEach(f=>f.texture.destroy());device.destroy()}
}
