import noiseAsset from '../../../../apps/web/src/engine/src/raster/watercolorNoise.txt?raw'
import {CanonicalFieldPasses} from '../../../../apps/web/src/engine/src/webgpuCanonical/passes/dispatcher'
import type {CanonicalGpuField,CanonicalPassResources} from '../../../../apps/web/src/engine/src/webgpuCanonical/types'
import type {Stage} from './stages'
export async function lazyFrontOracle(input:Stage,coverage:Stage,paperBytes:Uint8Array,paperSide:number,m:{x0:number;y0:number;scale:number;dryCost:number;max:number;climb:number;floor:number;stride:number},iterations=171,experiment:'lazy'|'static'='lazy'){
 const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw new Error('WebGPU unavailable');const timestamp=adapter.features.has('timestamp-query'),device=await adapter.requestDevice({requiredFeatures:timestamp?['timestamp-query']:[]}),fields:CanonicalGpuField[]=[],errors:string[]=[]
 device.addEventListener('uncapturederror',e=>errors.push(e.error.message))
 const field=(w:number,h:number,bytes?:Uint8Array)=>{const texture=device.createTexture({size:[w,h],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST}),f={width:w,height:h,texture,view:texture.createView(),label:'front lazy diagnostic',format:'rgba8unorm' as const,filter:'nearest' as const};fields.push(f);if(bytes)device.queue.writeTexture({texture},bytes.slice(),{bytesPerRow:w*4},[w,h]);return f}
 const read=async(f:CanonicalGpuField)=>{const pitch=Math.ceil(f.width*4/256)*256,b=device.createBuffer({size:pitch*f.height,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ}),e=device.createCommandEncoder();e.copyTextureToBuffer({texture:f.texture},{buffer:b,bytesPerRow:pitch},[f.width,f.height]);device.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const raw=new Uint8Array(b.getMappedRange()),out=new Uint8Array(f.width*f.height*4);for(let y=0;y<f.height;y++)out.set(raw.subarray(y*pitch,y*pitch+f.width*4),y*f.width*4);b.unmap();b.destroy();return out}
 const noiseBytes=Uint8Array.from(atob(noiseAsset),c=>c.charCodeAt(0)),rgba=new Uint8Array(noiseBytes.length*4);for(let i=0;i<noiseBytes.length;i++)rgba.set([noiseBytes[i],noiseBytes[i],noiseBytes[i],255],i*4)
 const noise=field(251,251,rgba),paper=field(paperSide,paperSide,paperBytes),gate=field(coverage.w,coverage.h,coverage.bytes),a=[field(input.w,input.h,input.bytes),field(input.w,input.h,input.bytes)],b=[field(input.w,input.h),field(input.w,input.h)],passes=new CanonicalFieldPasses(device)
 const resources=(src:CanonicalGpuField,out:CanonicalGpuField):CanonicalPassResources=>({a:src,b:src,coverage:gate,out,world:{x:0,y:0,width:input.w,height:input.h},paper:{field:paper,origin:[m.x0/m.scale,-(m.y0/m.scale+input.h)],texSize:[1024/m.scale,1024/m.scale],scale:1}})
 const nearest=device.createSampler(),linear=device.createSampler({minFilter:'linear',magFilter:'linear'})
 const encode=(src:CanonicalGpuField,out:CanonicalGpuField,lazy:boolean,timestampWrites?:GPUComputePassTimestampWrites,cachePrepTimestampWrites?:GPUComputePassTimestampWrites)=>{const encoder=device.createCommandEncoder();const uniform=passes.waterFront({device,encoder,nearest,linear},resources(src,out),noise,{dryCost:m.dryCost,costMax:m.max,climb:m.climb,floor:m.floor,stride:m.stride,diagnosticLazyClimb:lazy&&experiment==='lazy',diagnosticStaticCache:lazy&&experiment==='static',timestampWrites,cachePrepTimestampWrites});return{encoder,uniform}}
 const perIteration=[];let query:GPUQuerySet|undefined,resolve:GPUBuffer|undefined,staging:GPUBuffer|undefined,prepQuery:GPUQuerySet|undefined,prepResolve:GPUBuffer|undefined,prepRead:GPUBuffer|undefined;let cachePrepNanoseconds:number|null=null
 try{
  if(timestamp&&experiment==='static'){prepQuery=device.createQuerySet({type:'timestamp',count:2});prepResolve=device.createBuffer({size:256,usage:GPUBufferUsage.QUERY_RESOLVE|GPUBufferUsage.COPY_SRC});prepRead=device.createBuffer({size:16,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ})}
  for(let i=0;i<iterations;i++){for(let arm=0;arm<2;arm++){const prep=i===0&&arm===1&&prepQuery&&prepResolve&&prepRead;const cmd=encode(a[arm],b[arm],arm===1,undefined,prep?{querySet:prepQuery!,beginningOfPassWriteIndex:0,endOfPassWriteIndex:1}:undefined);if(prep){cmd.encoder.resolveQuerySet(prepQuery!,0,2,prepResolve!,0);cmd.encoder.copyBufferToBuffer(prepResolve!,0,prepRead!,0,16)}device.queue.submit([cmd.encoder.finish()]);await device.queue.onSubmittedWorkDone();cmd.uniform.destroy()}const old=await read(b[0]),next=await read(b[1]);let changed=0,max=0;for(let j=0;j<old.length;j++){let d=Math.abs(old[j]-next[j]);if(d)changed++;max=Math.max(max,d)}perIteration.push({iteration:i+1,changed,max});for(let arm=0;arm<2;arm++)[a[arm],b[arm]]=[b[arm],a[arm]]}
  if(prepRead){await prepRead.mapAsync(GPUMapMode.READ);const t=new BigUint64Array(prepRead.getMappedRange());cachePrepNanoseconds=Number(t[1]-t[0]);prepRead.unmap()}
  const gpuNanoseconds:{baseline:number[];lazy:number[]}={baseline:[],lazy:[]}
  if(timestamp){query=device.createQuerySet({type:'timestamp',count:2});resolve=device.createBuffer({size:256,usage:GPUBufferUsage.QUERY_RESOLVE|GPUBufferUsage.COPY_SRC});staging=device.createBuffer({size:16,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});for(let run=0;run<34;run++)for(const arm of run%2?[1,0]:[0,1]){device.queue.writeTexture({texture:a[arm].texture},input.bytes.slice(),{bytesPerRow:input.w*4},[input.w,input.h]);const cmd=encode(a[arm],b[arm],arm===1,{querySet:query,beginningOfPassWriteIndex:0,endOfPassWriteIndex:1});cmd.encoder.resolveQuerySet(query,0,2,resolve,0);cmd.encoder.copyBufferToBuffer(resolve,0,staging,0,16);device.queue.submit([cmd.encoder.finish()]);await staging.mapAsync(GPUMapMode.READ);const t=new BigUint64Array(staging.getMappedRange()),duration=Number(t[1]-t[0]);staging.unmap();cmd.uniform.destroy();if(run>=2)gpuNanoseconds[arm?'lazy':'baseline'].push(duration)}}
  return{experiment,cachePrepNanoseconds,cacheCounters:passes.staticCacheCounters,dimensions:[input.w,input.h],perIteration,exact:perIteration.every(p=>p.changed===0),timestampAvailable:timestamp,gpuNanoseconds,errors,limits:'Actual captured Q8 front input/coverage; same immutable paper/lattice, no foreignFilm; 171 repeated fixed stride gates, not a replacement planner schedule. Timestamp AB32 excludes readback and covers one front compute pass. Whole tape separately diagnostic OFF by default.'}
 }finally{prepQuery?.destroy();prepResolve?.destroy();prepRead?.destroy();query?.destroy();resolve?.destroy();staging?.destroy();fields.forEach(f=>f.texture.destroy());device.destroy()}
}
