import {CANONICAL_NOISE_WGSL} from '../../../../apps/web/src/engine/src/webgpuCanonical/noise'
import {RIBBON_FRAG} from '../../../../apps/web/src/engine/src/raster/shaders'
import noiseAsset from '../../../../apps/web/src/engine/src/raster/watercolorNoise.txt?raw'
import type {CanonicalWatercolorWebGpu} from '../../../../apps/web/src/engine/src/webgpuCanonical/backend'
const quantities=['lattice00','lattice10','lattice01','lattice11','fracX','fracY','noise','fbm'] as const
export function noisePointShaders(group:number){
 const n=['wcLattice(floor(point.xy))','wcLattice(floor(point.xy)+vec2f(1,0))','wcLattice(floor(point.xy)+vec2f(0,1))','wcLattice(floor(point.xy)+vec2f(1,1))','fract(point.x)','fract(point.y)','wcNoise(point.xy)','wcFbm(point.xy)'][group],g=['wcLattice(floor(p))','wcLattice(floor(p)+vec2(1,0))','wcLattice(floor(p)+vec2(0,1))','wcLattice(floor(p)+vec2(1,1))','fract(p.x)','fract(p.y)','wcNoise(p)','wcFbm(p)'][group]
 if(!n||!g)throw Error('Unknown noise point diagnostic')
 const start=RIBBON_FRAG.indexOf('uniform sampler2D u_wcNoiseTex;'),end=RIBBON_FRAG.indexOf('\n  void main()');if(start<0||end<start)throw Error('Literal GLSL noise extraction anchor missing')
 return{native:`@group(0) @binding(0) var<uniform> point:vec4f;@group(0) @binding(2) var noiseTex:texture_2d<f32>;${CANONICAL_NOISE_WGSL}@vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4f{let p=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));return vec4f(p[i],0,1);}@fragment fn fs()->@location(0) vec4f{let q=floor(clamp(${n},0,1)*16777215.0);return vec4f(floor(q/65536.0)/255.0,(floor(q/256.0)%256.0)/255.0,(q%256.0)/255.0,1);}`,gl:`precision highp float;uniform vec2 p;${RIBBON_FRAG.slice(start,end)}void main(){float q=floor(clamp(${g},0.0,1.0)*16777215.0);gl_FragColor=vec4(floor(q/65536.0)/255.0,mod(floor(q/256.0),256.0)/255.0,mod(q,256.0)/255.0,1.0);}`}
}
/** Same F32 uniform coordinates, no varying/raster or paper substitution. */
export async function noisePointOracle(owner:CanonicalWatercolorWebGpu){
 const f=Math.fround,across=f(-.536651135203667),drift=f(.5317890644073486),points=[[f(f(572.5*f(.0012))+71),f(f(588.5*f(.0012))+13)],[f(f(across*f(14.285714643669085))+3),f(f(drift*f(.9))+29)],[f(f(572.5*f(.009))+37),f(f(588.5*f(.009))+91)]]
 const device=owner.device,field=owner.createField('diagnostic noise point',1,1),uniform=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}),layout=device.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}},{binding:2,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'float'}}]}),pipelineLayout=device.createPipelineLayout({bindGroupLayouts:[layout]}),rows=[]
 try{for(let group=0;group<quantities.length;group++){
 const shaders=noisePointShaders(group),module=device.createShaderModule({code:shaders.native}),pipeline=device.createRenderPipeline({layout:pipelineLayout,vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format:'rgba8unorm'}]}}),bind=device.createBindGroup({layout,entries:[{binding:0,resource:{buffer:uniform}},{binding:2,resource:owner.noise.view}]}),glRows=glPoints(shaders.gl,points)
 for(let i=0;i<points.length;i++){device.queue.writeBuffer(uniform,0,new Float32Array([...points[i],0,0]));const encoder=device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:field.view,loadOp:'clear',storeOp:'store',clearValue:[0,0,0,0]}]});pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.draw(3);pass.end();device.queue.submit([encoder.finish()]);const native=Array.from(await owner.readField(field)),gl=glRows[i],decode=(a:number[])=>(a[0]*65536+a[1]*256+a[2])/16777215;rows.push({quantity:quantities[group],point:points[i],native,gl,nativeDecoded:decode(native),glDecoded:decode(gl)})}
 }}finally{uniform.destroy();owner.destroyField(field)}
 return{rows,scope:'Identical supplied F32 uniform noise coordinates and baked251lattice; no raster varyings/paper.24bit output quantization, not exactfloat readback; points are diagnostic CPU chosen, not claimed exact inherited hardware coordinates.'}
}
function glPoints(fragment:string,points:number[][]){const c=document.createElement('canvas');c.width=c.height=1;const gl=c.getContext('webgl',{antialias:false,preserveDrawingBuffer:true});if(!gl)throw Error('Noise GL unavailable');gl.disable(gl.DITHER);const compile=(type:number,code:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'Noise GL shader');return s},program=gl.createProgram()!;gl.attachShader(program,compile(gl.VERTEX_SHADER,'attribute vec2 a;void main(){gl_Position=vec4(a,0.,1.);}'));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||'Noise GL link');gl.useProgram(program);const tex=gl.createTexture()!;gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);gl.texImage2D(gl.TEXTURE_2D,0,gl.LUMINANCE,251,251,0,gl.LUMINANCE,gl.UNSIGNED_BYTE,Uint8Array.from(atob(noiseAsset),c=>c.charCodeAt(0)));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.uniform1i(gl.getUniformLocation(program,'u_wcNoiseTex'),0);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);gl.viewport(0,0,1,1);const rows=[];for(const point of points){gl.uniform2fv(gl.getUniformLocation(program,'p'),point);gl.drawArrays(gl.TRIANGLES,0,3);const bytes=new Uint8Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,bytes);rows.push(Array.from(bytes))}const error=gl.getError();gl.getExtension('WEBGL_lose_context')?.loseContext();if(error)throw Error('Noise GL error'+error);return rows}
