import {cancellationFreeBrushShader} from './cancellationFreeBrush'
import {encodeBrushShaderControl,encodeRawFlowBrush} from './brushRawFlowControl'
/// <reference types="@webgpu/types" />
import {CanonicalBrushContact} from '../../../../apps/web/src/engine/src/webgpuCanonical/brush'
import type {CanonicalGpuField} from '../../../../apps/web/src/engine/src/webgpuCanonical/types'
import {decodePreBrush68Checkpoint} from './preBrush68Codec'
import {BRUSH68_ROI,BRUSH68_SCISSOR,BRUSH68_FLOW_RECT} from './preBrush68Checkpoint'
const hash=async(b:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b.slice().buffer)),v=>v.toString(16).padStart(2,'0')).join('')
/** One original contact from COMMON actual old P/C/water; no source preparation,
 * no preceding native solver and no oracle overwrite between the two passes. */
export async function runPreBrush68NativeGate(packet:unknown,diagnosticRawGlFlow=false,chain?:{pulses:14;expected:readonly Uint8Array[]},diagnosticCancellationFreeFraction=false){
 if(diagnosticRawGlFlow&&diagnosticCancellationFreeFraction)throw Error('Independent brush controls only');if(chain&&(chain.pulses!==14||chain.expected.length!==2||chain.expected.some(b=>b.length!==127*108*4)))throw Error('Bounded original14 chain reference');const p=packet as any,input=await decodePreBrush68Checkpoint(p);if(!navigator.gpu)throw Error('WebGPU unsupported explicitly');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('WebGPU adapter unavailable');const device=await adapter.requestDevice(),textures:GPUTexture[]=[],buffers:GPUBuffer[]=[],errors:string[]=[];let lost=false
 device.addEventListener('uncapturederror',e=>errors.push(e.error.message));void device.lost.then(x=>{if(x.reason!=='destroyed')lost=true})
 const make=(label:string,width:number,height:number,filter:'nearest'|'linear'):CanonicalGpuField=>{const texture=device.createTexture({label,size:[width,height],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST});textures.push(texture);return{label,width,height,filter,format:'rgba8unorm',texture,view:texture.createView()}}
 try{device.pushErrorScope('validation');const pigment=make('COMMON original oldP',1536,1536,'nearest'),color=make('COMMON original oldC',1536,1536,'nearest'),water=make('COMMON original water',1536,1536,'nearest'),outP=make('contact P output',1536,1536,'nearest'),outC=make('contact C output',1536,1536,'nearest'),flow=make('original GLflow',31,26,'linear'),r=BRUSH68_ROI
  for(const [i,field]of [pigment,color,water].entries())device.queue.writeTexture({texture:field.texture,origin:[r.x,r.y]},input.rows[i].bytes,{bytesPerRow:r.width*4,rowsPerImage:r.height},[r.width,r.height])
  const flipped=new Uint8Array(input.flow.length);for(let y=0;y<26;y++)flipped.set(input.flow.subarray((25-y)*31*4,(26-y)*31*4),y*31*4);device.queue.writeTexture({texture:flow.texture},diagnosticRawGlFlow?input.flow:flipped,{bytesPerRow:124,rowsPerImage:26},[31,26])
  let oldP=pigment,oldC=color,nextP=outP,nextC=outC;const encoder=device.createCommandEncoder();encoder.copyTextureToTexture({texture:pigment.texture},{texture:outP.texture},[1536,1536]);encoder.copyTextureToTexture({texture:color.texture},{texture:outC.texture},[1536,1536]);const linear=device.createSampler({magFilter:'linear',minFilter:'linear',addressModeU:'clamp-to-edge',addressModeV:'clamp-to-edge'}),nearest=device.createSampler({magFilter:'nearest',minFilter:'nearest'}),ctx={device,encoder,linear,nearest},brush=new CanonicalBrushContact(device,true)
  // Original order and BOTH old references retained: C first, then P.
  const encode=(fields:any,output:'pigment'|'color')=>diagnosticCancellationFreeFraction?encodeBrushShaderControl(ctx,fields,output,.6437950134277344,BRUSH68_FLOW_RECT,BRUSH68_SCISSOR,cancellationFreeBrushShader()):diagnosticRawGlFlow?encodeRawFlowBrush(ctx,fields,output,.6437950134277344,BRUSH68_FLOW_RECT,BRUSH68_SCISSOR):brush.encodeSingle(ctx,fields,output,[1/1536,1/1536],.6437950134277344,BRUSH68_FLOW_RECT,BRUSH68_SCISSOR);for(let pulse=0;pulse<(chain?.pulses??1);pulse++){buffers.push(...encode({pigment:oldP,color:oldC,flow,water,out:nextC},'color'));buffers.push(...encode({pigment:oldP,color:oldC,flow,water,out:nextP},'pigment'));[oldP,nextP]=[nextP,oldP];[oldC,nextC]=[nextC,oldC]}
  const pitch=Math.ceil(r.width*4/256)*256,readbacks=[oldP,oldC].map(field=>{const b=device.createBuffer({size:pitch*r.height,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});buffers.push(b);encoder.copyTextureToBuffer({texture:field.texture,origin:[r.x,r.y]},{buffer:b,bytesPerRow:pitch,rowsPerImage:r.height},[r.width,r.height]);return b});device.queue.submit([encoder.finish()]);await device.queue.onSubmittedWorkDone();const comparisons=[]
  for(let i=0;i<2;i++){const b=readbacks[i];await b.mapAsync(GPUMapMode.READ);const mapped=new Uint8Array(b.getMappedRange()),actual=new Uint8Array(r.width*r.height*4);for(let y=0;y<r.height;y++)actual.set(mapped.subarray(y*pitch,y*pitch+r.width*4),y*r.width*4);b.unmap();const expected=chain?.expected[i]??input.rows[3+i].bytes,channels=Array.from({length:4},()=>({changed:0,max:0,sum:0})),examples=[];for(let k=0;k<actual.length;k++){const d=Math.abs(actual[k]-expected[k]),c=channels[k%4];if(d){c.changed++;if(examples.length<32)examples.push({x:r.x+Math.floor(k/4)%r.width,y:r.y+Math.floor(k/4/r.width),channel:k%4,expected:expected[k],actual:actual[k]})}c.max=Math.max(c.max,d);c.sum+=d}const sum=(b:Uint8Array)=>Array.from({length:4},(_,channel)=>{let total=0;for(let k=channel;k<b.length;k+=4)total+=b[k];return total}),beforeSum=sum(input.rows[i].bytes),actualSum=sum(actual),expectedSum=sum(expected),integrals={before:beforeSum,actual:actualSum,expected:expectedSum,actualMinusBefore:actualSum.map((n,c)=>n-beforeSum[c]),expectedMinusBefore:expectedSum.map((n,c)=>n-beforeSum[c])};const witnesses=[[349,288],[350,288]].map(([x,y])=>{const k=((y-r.y)*r.width+x-r.x)*4;return{x,y,expected:Array.from(expected.subarray(k,k+4)),actual:Array.from(actual.subarray(k,k+4))}});comparisons.push({role:['a','cc'][i],channels,examples,witnesses,integrals,expectedSha256:await hash(expected),actualSha256:await hash(actual),exact:channels.every(c=>c.changed===0)})}
  const validation=(await device.popErrorScope())?.message??null;return{code:'__SOURCE_CODE__',producerCode:p.code,pulses:chain?.pulses??1,diagnosticCancellationFreeFraction,diagnosticRawGlFlow,flowOrientation:diagnosticRawGlFlow?'GL-raw rows + direct localUV':'world-top rows + reflected localUV',operationSha256:p.operationSha256,paperSha256:p.paperSha256,roi:r,flowSha256:p.flow.sha256,comparisons,errors,lost,validation,scope:(chain?'Original14 brush68..81 C+P contacts, each API own Q8 state without reset; ':'One original brush68 C+P contact, ')+ ' COMMON actual GL precontact fields. Full1536 UV/filter/scissor preserved; only bounded ROI+2px halo initialized. Output material pair starts as oldP/C to model original region copyback; no claims outside ROI, actual working-field output siblings, whole solver, Room or performance.'}
 }finally{await device.queue.onSubmittedWorkDone().catch(()=>{});buffers.forEach(b=>b.destroy());textures.forEach(t=>t.destroy());device.destroy()}
}

export async function runPreBrush68FlowControl(packet:unknown){const baseline=await runPreBrush68NativeGate(packet,false),raw=await runPreBrush68NativeGate(packet,true);return{code:'__SOURCE_CODE__',arms:[baseline,raw],errors:[...baseline.errors,...raw.errors],lost:baseline.lost||raw.lost,validation:baseline.validation??raw.validation,scope:'QA OFF control: only flow row/UV orientation changes; two sequential native owners, same actual common oldP/C/water and unchanged fraction/floor body'}}

export async function runPreBrush68CancellationControl(packet:unknown){const baseline=await runPreBrush68NativeGate(packet),candidate=await runPreBrush68NativeGate(packet,false,undefined,true);return{code:'__SOURCE_CODE__',arms:[baseline,candidate],errors:[...baseline.errors,...candidate.errors],validation:baseline.validation??candidate.validation,lost:baseline.lost||candidate.lost,scope:'QA OFF: original GLreference UNCHANGED; native cancellation-free real-equivalent capacity algebra only. F32/Q8 order intentionally changes, noepsilon/biasedfloor/rawflow/physics tuning. One actual COMMON brush68 pair, no whole solver/Room or portable exactness claim'}}
