import {BRUSH68_ROI,BRUSH68_SCISSOR,BRUSH68_FLOW_RECT} from './preBrush68Checkpoint'
const hash=async(b:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b.slice().buffer)),v=>v.toString(16).padStart(2,'0')).join('')
export async function decodePreBrush68Checkpoint(packet:any){
 if(!packet?.glOwnerRetired||packet.glError!==0||packet.lost!==false||!/^[a-f0-9]{40}$/.test(packet.code)||JSON.stringify(packet.roi)!==JSON.stringify(BRUSH68_ROI)||packet.rows?.length!==6||packet.flow?.width!==31||packet.flow?.height!==26||packet.flow?.filter!=='linear'||packet.brushCalls?.length!==2)throw Error('Strict prebrush passport/geometry')
 const decode=async(r:any,n:number)=>{if(r.rawBytes!==n||!/^[a-f0-9]{64}$/.test(r.sha256)||!/^[a-f0-9]{64}$/.test(r.gzipSha256)||typeof r.gzipBase64!=='string'||r.gzipBase64.length>4*Math.ceil((n+8192)/3))throw Error('Prebrush raw/gzip bounds');const gz=Uint8Array.from(atob(r.gzipBase64),x=>x.charCodeAt(0));if(await hash(gz)!==r.gzipSha256)throw Error('Prebrush compressed checksum');const reader=new Blob([gz.buffer]).stream().pipeThrough(new DecompressionStream('gzip')).getReader(),bytes=new Uint8Array(n);let offset=0;try{while(true){const{done,value}=await reader.read();if(done)break;if(offset+value.length>n)throw Error('Prebrush inflate exceeds bound');bytes.set(value,offset);offset+=value.length}}finally{await reader.cancel().catch(()=>{})}if(offset!==n||await hash(bytes)!==r.sha256)throw Error('Prebrush raw checksum');return bytes}
 const rows=[];for(let i=0;i<6;i++){const r=packet.rows[i];if(r.phase!==(i<3?'before':'after')||r.role!==['a','cc','coverage'][i%3]||r.width!==1536||r.height!==1536||r.filter!=='nearest')throw Error('Prebrush role/order/filter');rows.push({...r,bytes:await decode(r,127*108*4)})}
 for(let i=0;i<2;i++){const c=packet.brushCalls[i];if(c.source!==['cc','a'][i]||c.radius!==4||c.scale!==1||c.gain!==.6437950134277344||JSON.stringify(c.scissor)!==JSON.stringify(BRUSH68_SCISSOR)||JSON.stringify(c.flowRect)!==JSON.stringify(BRUSH68_FLOW_RECT))throw Error('Original dualpass brush recipe')}
 const flow=await decode(packet.flow,3224);if(await hash(flow)!=='3be5473ac4b1fbe38bc49c2ffc943126572e988416f5b9b3694cd6e511bee43b')throw Error('Original flow checksum')
 return{rows,flow,roi:BRUSH68_ROI,scope:'ROI-only prebrush common input; outside halo not captured, fullfield SHA not claimed'}
}
