/// <reference types="@webgpu/types" />
import {DISPLAY_VERT,WC_FIELD_OP_HIGH_FRAG} from '../../../../apps/web/src/engine/src/raster/shaders'
import {CanonicalFieldOps} from '../../../../apps/web/src/engine/src/webgpuCanonical/passes/fieldOps'
import type {CanonicalGpuField} from '../../../../apps/web/src/engine/src/webgpuCanonical/types'
const W=1536,BYTES=W*W*4,hash=async(b:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b.slice().buffer)),x=>x.toString(16).padStart(2,'0')).join('')
export interface PressureSeedInput {producerCode:string;checkpointSha256:string;operationSha256:string;paperSha256:string;pigment:{gzipBase64:string;sha256:string};coverage:{gzipBase64:string;sha256:string};copyRect:[number,number,number,number,number,number];recipe:{k:number;band:[number,number];size:[number,number]};traceSha256:string}
async function decode(base64:string,bytes:number,expected:string){if(typeof base64!=='string'||base64.length>Math.ceil((bytes+8192)/3)*4||! /^[a-f0-9]{64}$/.test(expected))throw Error('Bounded compressed input schema');const gzip=Uint8Array.from(atob(base64),x=>x.charCodeAt(0)),reader=new Blob([gzip.buffer]).stream().pipeThrough(new DecompressionStream('gzip')).getReader(),out=new Uint8Array(bytes);let offset=0;try{while(true){const{done,value}=await reader.read();if(done)break;if(offset+value.length>bytes)throw Error('Input decompression bound');out.set(value,offset);offset+=value.length}}finally{await reader.cancel().catch(()=>{})}if(offset!==bytes||await hash(out)!==expected)throw Error('Durable input Q8 checksum');return out}
/** COPY of a proved original GL-bottom-up rect, into a cleared actual1536 field. */
export function reconstructPressureCoverage(source:Uint8Array,rect:PressureSeedInput['copyRect']){
 if(source.length!==1024*1024*4||rect.length!==6||rect.some(v=>!Number.isInteger(v)))throw Error('Actual copy rect schema');const[sx,sy,dx,dy,w,h]=rect;if(sx<0||sy<0||dx<0||dy<0||w<=0||h<=0||sx+w>1024||sy+h>1024||dx+w>W||dy+h>W)throw Error('Actual copy rect bound');const out=new Uint8Array(BYTES);for(let row=0;row<h;row++){const src=((1024-sy-h+row)*1024+sx)*4,dst=((W-dy-h+row)*W+dx)*4;out.set(source.subarray(src,src+w*4),dst)}return out
}
const flip=(b:Uint8Array)=>{const out=new Uint8Array(b.length);for(let y=0;y<W;y++)out.set(b.subarray(y*W*4,(y+1)*W*4),(W-y-1)*W*4);return out}
/** Isolated actual pressure mode10; paper/noise are not read by this branch.
 * Full source/solver repeats and artistic model changes are excluded. */
export async function runPressureSeedOracle(input:PressureSeedInput){
 if(!/^[a-f0-9]{40}$/.test(input.producerCode)||[input.checkpointSha256,input.operationSha256,input.paperSha256,input.traceSha256].some(s=>! /^[a-f0-9]{64}$/.test(s)))throw Error('Producer/input passport required')
 const p=await decode(input.pigment.gzipBase64,BYTES,input.pigment.sha256),source=await decode(input.coverage.gzipBase64,1024*1024*4,input.coverage.sha256),water=reconstructPressureCoverage(source,input.copyRect),recipe=input.recipe;if(recipe.k!==.003||recipe.band[1]!==1||![...recipe.band,...recipe.size].every(Number.isFinite))throw Error('Actual pressure recipe schema')
 let nonzero=0;for(const b of p)if(b)nonzero++;if(!nonzero)throw Error('Nontrivial actual pigment required');const inputHashes={pigment:await hash(p),coverageSource:await hash(source),coverageField:await hash(water)}
 const canvas=document.createElement('canvas');canvas.width=canvas.height=W;const gl=canvas.getContext('webgl',{preserveDrawingBuffer:true,premultipliedAlpha:false});if(!gl)throw Error('Actual WebGL unavailable');let expected:Uint8Array;let glError:number;const textures:WebGLTexture[]=[],shaders:WebGLShader[]=[];let program:WebGLProgram|null=null,buffer:WebGLBuffer|null=null,fb:WebGLFramebuffer|null=null
 try{
  const compile=(type:number,code:string)=>{const s=gl.createShader(type)!;shaders.push(s);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)??'GL shader');return s};program=gl.createProgram()!;gl.attachShader(program,compile(gl.VERTEX_SHADER,DISPLAY_VERT));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,WC_FIELD_OP_HIGH_FRAG));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)??'GL link');gl.useProgram(program)
  const texture=(bytes:Uint8Array|null)=>{const t=gl.createTexture()!;textures.push(t);gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,W,W,0,gl.RGBA,gl.UNSIGNED_BYTE,bytes);for(const q of[gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,q,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t};const a=texture(flip(p)),b=texture(flip(water)),out=texture(null);fb=gl.createFramebuffer()!;gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,out,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('GL field target incomplete');gl.viewport(0,0,W,W);gl.disable(gl.BLEND);gl.disable(gl.SCISSOR_TEST)
  buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'a_position');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0)
  for(let i=0;i<7;i++){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,i===1?b:a);gl.uniform1i(gl.getUniformLocation(program,['u_a','u_b','u_c','u_d','u_e','u_path','u_wcFibreNoiseTex'][i]),i)}
  gl.uniform1f(gl.getUniformLocation(program,'u_mode'),10);gl.uniform1f(gl.getUniformLocation(program,'u_k'),recipe.k);gl.uniform2fv(gl.getUniformLocation(program,'u_band'),recipe.band);gl.uniform2fv(gl.getUniformLocation(program,'u_size'),recipe.size);gl.uniform2fv(gl.getUniformLocation(program,'u_dir'),[1/W,1/W]);gl.drawArrays(gl.TRIANGLES,0,6);const raw=new Uint8Array(BYTES);gl.readPixels(0,0,W,W,gl.RGBA,gl.UNSIGNED_BYTE,raw);expected=flip(raw);glError=gl.getError();if(glError||gl.isContextLost())throw Error('GL error/loss')
 }finally{textures.forEach(t=>gl.deleteTexture(t));shaders.forEach(s=>gl.deleteShader(s));gl.deleteProgram(program);gl.deleteBuffer(buffer);gl.deleteFramebuffer(fb);gl.getExtension('WEBGL_lose_context')?.loseContext()}
 // Own GL retired before native allocation; only immutable CPU input/reference remain.
 const adapter=await navigator.gpu?.requestAdapter();if(!adapter)throw Error('Native adapter unavailable');const device=await adapter.requestDevice(),fields:CanonicalGpuField[]=[],errors:string[]=[];device.addEventListener('uncapturederror',e=>errors.push(e.error.message));let lost=false;void device.lost.then(x=>{if(x.reason!=='destroyed')lost=true});let read:GPUBuffer|undefined,uniform:GPUBuffer|undefined
 try{
  const field=(bytes?:Uint8Array)=>{const texture=device.createTexture({size:[W,W],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC|GPUTextureUsage.COPY_DST});const f={texture,view:texture.createView(),width:W,height:W,format:'rgba8unorm' as const,filter:'nearest' as const,label:'actual pressure input/output'};fields.push(f);if(bytes)device.queue.writeTexture({texture},bytes,{bytesPerRow:W*4},{width:W,height:W});return f};const a=field(p),b=field(water),out=field(),encoder=device.createCommandEncoder();device.pushErrorScope('validation');uniform=new CanonicalFieldOps(device).run({device,encoder,nearest:device.createSampler({magFilter:'nearest',minFilter:'nearest'}),linear:device.createSampler({magFilter:'linear',minFilter:'linear'})},{a,b,c:a,coverage:b,paper:{field:a,origin:[0,0],texSize:[1024,1024],scale:1},out,world:{x:0,y:0,width:W,height:W}},10,recipe.k,{band:recipe.band,size:recipe.size});read=device.createBuffer({size:BYTES,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});encoder.copyTextureToBuffer({texture:out.texture},{buffer:read,bytesPerRow:W*4},{width:W,height:W});device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const actual=new Uint8Array(read.getMappedRange()).slice(),validation=(await device.popErrorScope())?.message??null,channels=Array.from({length:4},()=>({changed:0,max:0,sum:0}));for(let i=0;i<BYTES;i++){const d=Math.abs(actual[i]-expected![i]),c=channels[i%4];if(d)c.changed++;c.max=Math.max(c.max,d);c.sum+=d}return{code:'__SOURCE_CODE__',producerCode:input.producerCode,inputHashes,recipe,copyRect:input.copyRect,mode:10,width:W,height:W,filter:'nearest',glDither:true,pigmentNonzeroBytes:nonzero,glOwnerRetired:true,glError:glError!,lost,errors,validation,expectedSha256:await hash(expected!),actualSha256:await hash(actual),channels,exact:channels.every(c=>c.changed===0),limits:'Captured actual single-color c + source coverage, proved copyRect reconstructed into cleared1536 field. Only actual fieldOp10 shaders. No paper/noise access in this branch; no full solver/Room/performance claim.'}
 }finally{read?.destroy();uniform?.destroy();fields.forEach(f=>f.texture.destroy());device.destroy()}
}
