/// <reference types="@webgpu/types" />
import {DISPLAY_VERT,WC_FIELD_OP_FRAG} from '../../../../apps/web/src/engine/src/raster/shaders'
import {CANONICAL_FIELD_OPS_WGSL} from '../../../../apps/web/src/engine/src/webgpuCanonical/passes/fieldOps'
export const RIM_PROBE_CELLS=[[324,267],[326,267],[327,267],[327,271]] as const
export function rimNoiseFloatShaders(){
 const gs=WC_FIELD_OP_FRAG.indexOf('float wcRimHash(vec2 p)'),ge=WC_FIELD_OP_FRAG.indexOf('// (#680, s17.87)',gs),ws=CANONICAL_FIELD_OPS_WGSL.indexOf('fn rimHash('),we=CANONICAL_FIELD_OPS_WGSL.indexOf('fn lattice(',ws)
 if(gs<0||ge<gs||ws<0||we<ws)throw Error('Exact original rim hash/noise anchors required')
 const gl=`precision highp float;uniform vec2 u_p0;uniform vec2 u_p1;uniform vec2 u_p2;uniform vec2 u_p3;uniform vec3 u_world;\n${WC_FIELD_OP_FRAG.slice(gs,ge)}\nvoid main(){vec2 p=u_p0;if(gl_FragCoord.x>1.0)p=u_p1;if(gl_FragCoord.x>2.0)p=u_p2;if(gl_FragCoord.x>3.0)p=u_p3;vec2 wp=(p+u_world.xy)*u_world.z*0.012;float first=wcRimNoise(wp);float second=wcRimNoise(wp*2.7+vec2(31.4,17.9));float n=0.63*first+0.37*second;float patch=mix(0.1,1.0,smoothstep(0.45,0.6,n));gl_FragColor=vec4(first,second,n,patch);}`
 const native=`struct U{points:array<vec4f,4>,world:vec4f};@group(0) @binding(0)var<uniform>u:U;@group(0) @binding(1)var output:texture_storage_2d<rgba32float,write>;\n${CANONICAL_FIELD_OPS_WGSL.slice(ws,we)}\n@compute @workgroup_size(4)fn main(@builtin(global_invocation_id)id:vec3u){if(id.x>=4u){return;}let wp=(u.points[id.x].xy+u.world.xy)*u.world.z*.012;let first=rimNoise(wp);let second=rimNoise(wp*2.7+vec2f(31.4,17.9));let n=.63*first+.37*second;let patchValue=mix(.1,1.0,smoothstep(.45,.6,n));textureStore(output,vec2i(i32(id.x),0),vec4f(first,second,n,patchValue));}`
 return {gl,native}
}
/** Four64byte outputs only; extracted helpers, not complete mode6 float execution.
 * Existing actual rimPatchOFF control is the source-boundary causal evidence. */
export async function runRimNoiseFloatOracle(){
 const codes=rimNoiseFloatShaders(),canvas=document.createElement('canvas');canvas.width=4;canvas.height=1;const gl=canvas.getContext('webgl',{premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)throw Error('Rim float GL unavailable');const shaders:WebGLShader[]=[];let program:WebGLProgram|null=null,buffer:WebGLBuffer|null=null,texture:WebGLTexture|null=null,fb:WebGLFramebuffer|null=null;const expected=new Float32Array(16)
 try{
  if(!gl.getExtension('OES_texture_float')||!gl.getExtension('WEBGL_color_buffer_float'))throw Error('Explicit unsupported GL float framebuffer')
  program=gl.createProgram()!;for(const[type,code]of[[gl.VERTEX_SHADER,DISPLAY_VERT],[gl.FRAGMENT_SHADER,codes.gl]] as const){const s=gl.createShader(type)!;shaders.push(s);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)??'Rim float shader');gl.attachShader(program,s)}gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)??'Rim float link');gl.useProgram(program);texture=gl.createTexture()!;gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,4,1,0,gl.RGBA,gl.FLOAT,null);for(const k of[gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,k,gl.NEAREST);fb=gl.createFramebuffer()!;gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Explicit unsupported actual GL float target');gl.viewport(0,0,4,1);gl.disable(gl.BLEND);buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'a_position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);RIM_PROBE_CELLS.forEach(([x,y],i)=>gl.uniform2f(gl.getUniformLocation(program!,'u_p'+i),x+.5,1536-y-.5));gl.uniform3f(gl.getUniformLocation(program,'u_world'),0,-1576,1);gl.drawArrays(gl.TRIANGLES,0,6);gl.readPixels(0,0,4,1,gl.RGBA,gl.FLOAT,expected);if(gl.getError()||gl.isContextLost()||expected.some(v=>!Number.isFinite(v)))throw Error('GL rim float readback error')
 }finally{shaders.forEach(s=>gl.deleteShader(s));gl.deleteProgram(program);gl.deleteBuffer(buffer);gl.deleteTexture(texture);gl.deleteFramebuffer(fb);gl.getExtension('WEBGL_lose_context')?.loseContext()}
 const adapter=await navigator.gpu?.requestAdapter();if(!adapter)throw Error('Native rim float unavailable');const device=await adapter.requestDevice();let textureGpu:GPUTexture|undefined,uniform:GPUBuffer|undefined,read:GPUBuffer|undefined,lost=false;const errors:string[]=[];device.addEventListener('uncapturederror',e=>errors.push(e.error.message));void device.lost.then(i=>{if(i.reason!=='destroyed')lost=true})
 try{
  device.pushErrorScope('validation');const module=device.createShaderModule({code:codes.native}),info=await module.getCompilationInfo();if(info.messages.some(m=>m.type==='error'))throw Error('Native rim float compile: '+info.messages.filter(m=>m.type==='error').map(m=>m.lineNum+':'+m.message).join('; '));const pipeline=device.createComputePipeline({layout:'auto',compute:{module,entryPoint:'main'}});const values=new Float32Array(20);RIM_PROBE_CELLS.forEach(([x,y],i)=>values.set([x+.5,1536-y-.5,0,0],i*4));values.set([0,-1576,1,0],16);uniform=device.createBuffer({size:80,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(uniform,0,values);textureGpu=device.createTexture({size:[4,1],format:'rgba32float',usage:GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.COPY_SRC});const bind=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:uniform}},{binding:1,resource:textureGpu.createView()}]}),encoder=device.createCommandEncoder(),pass=encoder.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.dispatchWorkgroups(1);pass.end();read=device.createBuffer({size:256,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});encoder.copyTextureToBuffer({texture:textureGpu},{buffer:read,bytesPerRow:256},{width:4,height:1});device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const actual=new Float32Array(read.getMappedRange().slice(0,64)),validation=(await device.popErrorScope())?.message??null;if(actual.some(v=>!Number.isFinite(v)))throw Error('Nonfinite native rim float');const names=['firstNoise','secondNoise','weightedNoise','rimPatch'],eb=new Uint32Array(expected.buffer),ab=new Uint32Array(actual.buffer);return {code:'__SOURCE_CODE__',operator:'rimNoiseFloatExtracted',rows:RIM_PROBE_CELLS.map(([x,y],i)=>({x,y,values:names.map((name,k)=>({name,gl:expected[i*4+k],native:actual[i*4+k],glBits:eb[i*4+k],nativeBits:ab[i*4+k],difference:actual[i*4+k]-expected[i*4+k]}))})),errors,glError:0,lost,validation,glOwnerRetired:true,limits:'Extracted original helpers on identical uniforms/no varying/inputtextures. Optimizer may differ from fullmode6; not finalQ8/Room/performance or instruction cause proof.'}
 }finally{read?.destroy();uniform?.destroy();textureGpu?.destroy();device.destroy()}
}
