import type {CanonicalWatercolorWebGpu} from '../../../../apps/web/src/engine/src/webgpuCanonical/backend'
export const sourceBlendAmounts=[0.001959025976599811,0.0019673110227174176,1/510,0.0019,0.0021] as const
/** Same literal F32 source and initial6/255; bypasses all watercolor/noise/raster inputs. */
export async function scalarBlendOracle(owner:CanonicalWatercolorWebGpu){
 const device=owner.device,field=owner.createField('diagnostic scalar blend',1,1),uniform=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}),rows=[]
 const module=device.createShaderModule({code:'@group(0) @binding(0) var<uniform> amount:vec4f; @vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4f {let p=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));return vec4f(p[i],0,1);} @fragment fn fs()->@location(0) vec4f{return vec4f(0,0,amount.x,amount.x);}'})
 const pipeline=device.createRenderPipeline({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format:'rgba8unorm',blend:{color:{operation:'add',srcFactor:'one',dstFactor:'one-minus-src-alpha'},alpha:{operation:'add',srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]}}),group=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:uniform}}]})
 try{for(const supplied of sourceBlendAmounts){const value=Math.fround(supplied);device.queue.writeBuffer(uniform,0,new Float32Array([value,0,0,0]));owner.upload(field,new Uint8Array([0,0,6,6]));const encoder=device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:field.view,loadOp:'load',storeOp:'store'}]});pass.setPipeline(pipeline);pass.setBindGroup(0,group);pass.draw(3);pass.end();device.queue.submit([encoder.finish()]);rows.push({value,native:Array.from(await owner.readField(field)),gl:flatGl(value),idealUnquantized:6+(255-6)*value,sourceByte:Math.round(value*255)})}}
 finally{uniform.destroy();owner.destroyField(field)}
 return{rows,scope:'One1px RGBA8 OVER, identical F32 source uniform and initial[0,0,6,6], DITHERdisabled, no watercolor. Boundary-only driver behavior, not generalized model parity.'}
}
function flatGl(amount:number){const c=document.createElement('canvas');c.width=c.height=1;const gl=c.getContext('webgl',{antialias:false,preserveDrawingBuffer:true});if(!gl)throw Error('GL scalar oracle unavailable');gl.disable(gl.DITHER)
 const compile=(type:number,code:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'Scalar shader');return s},program=gl.createProgram()!;gl.attachShader(program,compile(gl.VERTEX_SHADER,'attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}'));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,'precision highp float;uniform float amount;void main(){gl_FragColor=vec4(0.,0.,amount,amount);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Scalar link');gl.useProgram(program);gl.uniform1f(gl.getUniformLocation(program,'amount'),amount)
 const tex=gl.createTexture()!;gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([0,0,6,6]));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);const fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);gl.viewport(0,0,1,1);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.TRIANGLES,0,3);const bytes=new Uint8Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,bytes);const error=gl.getError();gl.getExtension('WEBGL_lose_context')?.loseContext();if(error)throw Error('Scalar GL error'+error);return Array.from(bytes)}
