import {AccumulationBuffer} from '../../../../apps/web/src/engine/src/buffers/AccumulationBuffer'
import {CanonicalFieldBuffer} from '../../../../apps/web/src/engine/src/webgpuCanonical/fieldBuffer'
import {installSolverCheckpointOps} from './solverCheckpointOps.mjs'
const FIELD_BYTES=1536*1536*4
const hash=async(bytes:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes.slice().buffer)),v=>v.toString(16).padStart(2,'0')).join('')
const flip=(raw:Uint8Array)=>{const top=new Uint8Array(raw.length);for(let y=0;y<1536;y++)top.set(raw.subarray((1535-y)*6144,(1536-y)*6144),y*6144);return top}
export interface SolverBoundarySnapshot {index:0|1;trace:unknown[];roles:Array<{role:string;w:1536;h:1536;filter:'nearest'|'linear';sha256:string;gzipSha256:string;gzipBase64:string}>}
/** Two exact Q8 fields at ONE original operator boundary; no operator math changed. */
export function installBoundarySnapshot(owner:any,native:boolean,index:0|1){
 const planner=native?owner.planner:owner._settlePlan,buffers:any[]=[],trace:unknown[]=[]
 const describe=(b:any)=>b?{w:b.width,h:b.height,filter:b.filter??b._baseFilter}:null
 const capture=installSolverCheckpointOps(planner,{indices:[index],beforeOperation:()=>{
  const passes=planner.ctx.passes(),proto=native?CanonicalFieldBuffer.prototype:AccumulationBuffer.prototype,copy=proto.copyRegionInto,resample=passes.wcResample,fieldOp=passes.fieldOp
  proto.copyRegionInto=function(this:any,out:any,...args:any[]){trace.push({kind:'copyRegionInto',source:describe(this),out:describe(out),args});return(copy as any).call(this,out,...args)} as any
  passes.wcResample=function(...args:any[]){trace.push({kind:'wcResample',out:describe(args[0]),source:describe(args[5]),rect:args.slice(1,5),sourceOrigin:args.slice(6,8),ratio:args[8],mode:args[9],clamp:args[12]??null});return resample.apply(this,args)}
  passes.fieldOp=function(...args:any[]){trace.push({kind:'fieldOp',out:describe(args[0]),a:describe(args[1]),b:describe(args[2]),mode:args[3],k:args[4]});return fieldOp.apply(this,args)}
  return()=>{proto.copyRegionInto=copy;passes.wcResample=resample;passes.fieldOp=fieldOp}
 },rolesForIndex:()=>index===0?['a','ca']:['c','cc'],getField:()=>native?owner.fieldOwner.current:owner._fieldCache[0],clone:source=>{
  if(source.width!==1536||source.height!==1536)throw Error('Exact1536 source required')
  if(native){const out=new CanonicalFieldBuffer(owner.backend,1536,1536,source.filter,'QA boundary snapshot');buffers.push(out);source.copyTo(out);return out}
  const gl=owner.gl as WebGLRenderingContext,fb=gl.getParameter(gl.FRAMEBUFFER_BINDING),active=gl.getParameter(gl.ACTIVE_TEXTURE),texture=gl.getParameter(gl.TEXTURE_BINDING_2D),viewport=gl.getParameter(gl.VIEWPORT),clear=gl.getParameter(gl.COLOR_CLEAR_VALUE)
  try{const out=new AccumulationBuffer(gl,1536,1536,source._baseFilter);buffers.push(out);source.copyTo(out);return out}finally{gl.activeTexture(active);gl.bindTexture(gl.TEXTURE_2D,texture);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.viewport(...Array.from(viewport) as[number,number,number,number]);gl.clearColor(...Array.from(clear) as[number,number,number,number])}
 }})
 return{async read(){if(capture.captures.length!==1||capture.calls!==1)throw Error('Exactly one original operator snapshot required');const row=capture.captures[0],roles=[];for(const role of index===0?['a','ca']:['c','cc']){const b=row[role],bytes=native?await b.readBytes():flip(b.readPixels());if(bytes.length!==FIELD_BYTES)throw Error('Bounded field bytes');roles.push({role,w:1536 as const,h:1536 as const,filter:(b.filter??b._baseFilter) as 'nearest'|'linear',bytes})}return{index,trace,roles}},destroy(){capture.detach();for(const b of buffers)b.destroy()}}
}
export async function packBoundarySnapshot(snapshot:Awaited<ReturnType<ReturnType<typeof installBoundarySnapshot>['read']>>):Promise<SolverBoundarySnapshot>{
 const roles=[];for(const r of snapshot.roles){const gzip=new Uint8Array(await new Response(new Blob([r.bytes.slice().buffer]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());if(gzip.length>FIELD_BYTES+8192)throw Error('Gzip field bound');let s='';for(let i=0;i<gzip.length;i+=32768)s+=String.fromCharCode(...gzip.subarray(i,i+32768));roles.push({role:r.role,w:r.w,h:r.h,filter:r.filter,sha256:await hash(r.bytes),gzipSha256:await hash(gzip),gzipBase64:btoa(s)})}return{index:snapshot.index,trace:snapshot.trace,roles}
}
export async function validateBoundarySnapshot(snapshot:SolverBoundarySnapshot){
 if(!snapshot||![0,1].includes(snapshot.index)||!Array.isArray(snapshot.trace)||snapshot.trace.length>64||!Array.isArray(snapshot.roles)||snapshot.roles.length!==2)throw Error('Strict boundary schema');const names=snapshot.index===0?['a','ca']:['c','cc']
 for(let i=0;i<2;i++){const r=snapshot.roles[i];if(r.role!==names[i]||r.w!==1536||r.h!==1536||r.filter!=='nearest'||!/^[a-f0-9]{64}$/.test(r.sha256)||!/^[a-f0-9]{64}$/.test(r.gzipSha256)||typeof r.gzipBase64!=='string'||r.gzipBase64.length>Math.ceil((FIELD_BYTES+8192)/3)*4)throw Error('Strict boundary dimensions/filter/hash/budget');const gz=Uint8Array.from(atob(r.gzipBase64),x=>x.charCodeAt(0));if(gz.length>FIELD_BYTES+8192||await hash(gz)!==r.gzipSha256)throw Error('Strict boundary compressed checksum');const reader=new Blob([gz.buffer]).stream().pipeThrough(new DecompressionStream('gzip')).getReader(),bytes=new Uint8Array(FIELD_BYTES);let offset=0;try{while(true){const{done,value}=await reader.read();if(done)break;if(offset+value.length>FIELD_BYTES)throw Error('Strict boundary decompression bound');bytes.set(value,offset);offset+=value.length}}finally{await reader.cancel().catch(()=>{})}if(offset!==FIELD_BYTES||await hash(bytes)!==r.sha256)throw Error('Strict boundary raw checksum')}
}
export async function compareBoundarySnapshot(actual:Awaited<ReturnType<ReturnType<typeof installBoundarySnapshot>['read']>>,expected:SolverBoundarySnapshot){
 await validateBoundarySnapshot(expected);if(actual.index!==expected.index||expected.roles.length!==2)throw Error('Original boundary/role count mismatch');const traceExact=JSON.stringify(actual.trace)===JSON.stringify(expected.trace);if(!traceExact)throw Error('Boundary actual copy/resample/fieldOp dimensions/filter/rect/mode mismatch');const rows=[]
 for(const r of actual.roles){const e=expected.roles.find(x=>x.role===r.role);if(!e||e.w!==r.w||e.h!==r.h||e.filter!==r.filter)throw Error('Boundary dims/filter/role mismatch');const gz=Uint8Array.from(atob(e.gzipBase64),x=>x.charCodeAt(0));if(gz.length>FIELD_BYTES+8192||await hash(gz)!==e.gzipSha256)throw Error('Boundary compressed SHA mismatch');const reader=new Blob([gz.buffer]).stream().pipeThrough(new DecompressionStream('gzip')).getReader(),bytes=new Uint8Array(FIELD_BYTES);let offset=0;try{while(true){const{done,value}=await reader.read();if(done)break;if(offset+value.length>FIELD_BYTES)throw Error('Boundary decompression bound');bytes.set(value,offset);offset+=value.length}}finally{await reader.cancel().catch(()=>{})}if(offset!==FIELD_BYTES||await hash(bytes)!==e.sha256)throw Error('Boundary Q8 SHA mismatch');const channels=Array.from({length:4},()=>({changed:0,max:0,sum:0}));for(let i=0;i<bytes.length;i++){const d=Math.abs(bytes[i]-r.bytes[i]),c=channels[i%4];if(d)c.changed++;c.max=Math.max(c.max,d);c.sum+=d}rows.push({role:r.role,w:r.w,h:r.h,filter:r.filter,expectedSha256:e.sha256,actualSha256:await hash(r.bytes),channels,exact:channels.every(c=>c.changed===0)})
 }return{index:actual.index,traceExact,trace:actual.trace,rows,scope:'One original operator boundary, two actual1536 Q8 fields; field filter checked. No whole solver/Room claim.'}
}
